Move the mdbcomp library to its own directory.
Estimated hours taken: 12
Branches: main

Move the mdbcomp library to its own directory. To make this change less painful
to test, improve the way we handle installs.

browser/mdbcomp.m:
browser/mer_mdbcomp.m:
browser/prim_data.m:
browser/program_representation.m:
browser/trace_counts.m:
	Move these files to the mdbcomp directory.

browser/Mmakefile:
browser/Mercury.options:
mdbcomp/Mmakefile:
mdbcomp/Mercury.options:
	Split the contents of the old Mmakefile and Mercury.options file
	in the browser directory between these files as appropriate.
	Simplify away the stuff not needed now that there is only one library
	per directory. Make the browser directory see the relevant files
	from the mdbcomp directory.

Mmake.common.in:
	Separate out the prefixes allowed in the browser and the mdbcomp
	directories.

Mmake.workspace:
	Set up a make variable to refer to the mdbcomp directory.

	Adjust references to the mdbcomp library to point to its new location.

Mmakefile:
	Make invocations visit the mdbcomp library as necessary.

	Improve the way we install grades. Making temporary backups of the
	directories modified by the install process is unsatisfactory for two
	reasons. First, if the install fails, the cleanup script, which is
	necessary for user friendliness, destroys any evidence of the cause.
	Second, the restore of the backup wasn't perfect, e.g. it left the
	.d files modified to depend on .mih files, which don't exist in
	LLDS grades, and also left altered timestamps.

	This diff changes the install process to make a single tmp_dir
	subdirectory of the workspace, with all the work of install_grade
	being done inside tmp_dir. The original directories aren't touched
	at all.

*/Mmakefile:
	Adjust references to the browser directory to refer to the mdbcomp
	directory instead or as well.

scripts/Mmake.rules:
*/Mmakefile:
	Make it easier to debug Mmakefiles. Previously, creating a
	Mmake.makefile with mmake -s and invoking "make -d" ignored the
	most fundamental rules of mmake, because Mmake.rules was treating
	an unset MMAKE_USE_MMC_MAKE as if it were set to "yes", simply because
	it was different from "no". This diff changes it to treat an unset
	MMAKE_USE_MMC_MAKE as if it were set to "no", which is a more
	sensible default.

scripts/prepare_tmp_dir_fixed_part.in:
scripts/scripts/prepare_tmp_dir_grade_part:
	Two new scripts that each do half the work of preparing tmp_dir for
	the real work of the install_grade make target. The fixed_part script
	prepares the parts of tmp_dir that are grade-independent, while the
	grade_part scripts prepares the parts that are grade-dependent.

configure.in:
	Test C files in the mdbcomp directory to see whether they need to
	be recompiled after reconfiguration.

	Create prepare_tmp_dir_fixed_part from prepare_tmp_dir_fixed_part.in.

compiler/*.m:
runtime/mercury_wrapper.c:
	Update the references to the moved files.

compiler/notes/overall_design.html:
	Mention the new directory.

diff --git a/Mmakefile b/Mmakefile
--- a/Mmakefile
+++ b/Mmakefile
@@ -1,5 +1,5 @@
 #-----------------------------------------------------------------------------#
-# Copyright (C) 1995-2004 The University of Melbourne. 
+# Copyright (C) 1995-2005 The University of Melbourne.
 # This file may only be copied under the terms of the GNU General
 # Public Licence - see the file COPYING in the Mercury distribution.
 #-----------------------------------------------------------------------------#
@@ -30,6 +30,7 @@ SUBDIRS = \
 		robdd \
 		library \
 		trace \
+		mdbcomp \
 		browser \
 		analysis \
 		compiler \
@@ -57,8 +58,8 @@ GENERATED_DOCS = README INSTALL WORK_IN_PROGRESS TODO
 RT_LIB_NAME = mer_rt
 STD_LIB_NAME = mer_std
 TRACE_LIB_NAME = mer_trace
-BROWSER_LIB_NAME = mer_browser
 MDBCOMP_LIB_NAME = mer_mdbcomp
+BROWSER_LIB_NAME = mer_browser
 ANALYSIS_LIB_NAME = mer_analysis
 
 #-----------------------------------------------------------------------------#
@@ -67,7 +68,7 @@ ANALYSIS_LIB_NAME = mer_analysis
 # `mmake depend' forces them to be remade to ensure that they are up-to-date.
 
 .PHONY: dep
-dep: dep_library dep_browser dep_analysis dep_compiler \
+dep: dep_library dep_mdbcomp dep_browser dep_analysis dep_compiler \
 		dep_profiler dep_deep_profiler
 
 .PHONY: dep_library
@@ -76,16 +77,19 @@ dep_library: library/$(deps_subdir)$(STD_LIB_NAME).dep
 library/$(deps_subdir)$(STD_LIB_NAME).dep:
 	+cd library && $(SUBDIR_MMAKE) depend
 
+.PHONY: dep_mdbcomp
+dep_mdbcomp: \
+	mdbcomp/$(deps_subdir)$(MDBCOMP_LIB_NAME).dep
+
+mdbcomp/$(deps_subdir)$(MDBCOMP_LIB_NAME).dep:
+	+cd mdbcomp && $(SUBDIR_MMAKE) $(MDBCOMP_LIB_NAME).depend
+
 .PHONY: dep_browser
 dep_browser: \
-	browser/$(deps_subdir)$(BROWSER_LIB_NAME).dep \
-	browser/$(deps_subdir)$(MDBCOMP_LIB_NAME).dep
+	browser/$(deps_subdir)$(BROWSER_LIB_NAME).dep
 
 browser/$(deps_subdir)$(BROWSER_LIB_NAME).dep:
 	+cd browser && $(SUBDIR_MMAKE) $(BROWSER_LIB_NAME).depend
-
-browser/$(deps_subdir)$(MDBCOMP_LIB_NAME).dep:
-	+cd browser && $(SUBDIR_MMAKE) $(MDBCOMP_LIB_NAME).depend
 
 .PHONY: dep_analysis
 dep_analysis: analysis/$(deps_subdir)$(ANALYSIS_LIB_NAME).dep
@@ -127,6 +131,7 @@ deep_profiler/$(deps_subdir)mdprof_test.dep: \
 .PHONY: depend
 depend:
 	+cd library && $(SUBDIR_MMAKE) depend
+	+cd mdbcomp && $(SUBDIR_MMAKE) depend
 	+cd browser && $(SUBDIR_MMAKE) depend
 	+cd analysis && $(SUBDIR_MMAKE) depend
 	+cd compiler && $(SUBDIR_MMAKE) depend
@@ -136,6 +141,10 @@ depend:
 .PHONY: depend_library
 depend_library:
 	+cd library && $(SUBDIR_MMAKE) depend
+
+.PHONY: depend_mdbcomp
+depend_mdbcomp:
+	+cd mdbcomp && $(SUBDIR_MMAKE) depend
 
 .PHONY: depend_browser
 depend_browser:
@@ -183,26 +192,31 @@ robdd: scripts boehm_gc
 library: dep_library scripts util boehm_gc runtime
 	+cd library && $(SUBDIR_MMAKE)
 
+.PHONY: mdbcomp
+mdbcomp: dep_mdbcomp scripts util boehm_gc runtime library
+	+cd mdbcomp && $(SUBDIR_MMAKE)
+
 .PHONY: browser
-browser: dep_browser scripts util boehm_gc runtime library
+browser: dep_browser scripts util boehm_gc runtime library mdbcomp
 	+cd browser && $(SUBDIR_MMAKE)
 
 .PHONY: analysis
-analysis: dep_analysis scripts util boehm_gc runtime library browser trace
+analysis: dep_analysis scripts util boehm_gc runtime library mdbcomp browser \
+		trace
 	+cd analysis && $(SUBDIR_MMAKE)
 
 .PHONY: runtime
-trace: scripts boehm_gc runtime library browser
+trace: scripts boehm_gc runtime library mdbcomp browser
 	+cd trace && $(SUBDIR_MMAKE)
 
 .PHONY: compiler
 compiler: dep_compiler scripts util boehm_gc runtime library \
-		browser trace analysis
+		mdbcomp browser trace analysis
 	+cd compiler && $(SUBDIR_MMAKE)
 
 .PHONY: libmmc
 libmmc: dep_compiler scripts util boehm_gc runtime library \
-		browser trace analysis
+		mdbcomp browser trace analysis
 	+cd compiler && $(SUBDIR_MMAKE) libmmc
 
 .PHONY: doc
@@ -210,18 +224,19 @@ doc: scripts util
 	+cd doc && $(SUBDIR_MMAKE)
 
 .PHONY: profiler
-profiler: dep_profiler scripts util boehm_gc runtime library browser trace
+profiler: dep_profiler scripts util boehm_gc runtime library \
+		mdbcomp browser trace
 	+cd profiler && $(SUBDIR_MMAKE)
 
 .PHONY: deep_profiler
 deep_profiler: dep_deep_profiler scripts util boehm_gc runtime library \
-		browser trace
+		mdbcomp browser trace
 	+cd deep_profiler && $(SUBDIR_MMAKE)
 
 #-----------------------------------------------------------------------------#
 
 .PHONY: tags
-tags: tags_compiler tags_library tags_browser tags_analysis \
+tags: tags_compiler tags_library tags_mdbcomp tags_browser tags_analysis \
 		tags_profiler tags_deep_profiler
 
 .PHONY: tags_compiler
@@ -231,6 +246,10 @@ tags_compiler:
 .PHONY: tags_library
 tags_library:
 	+cd library && $(SUBDIR_MMAKE) tags
+
+.PHONY: tags_mdbcomp
+tags_mdbcomp:
+	+cd mdbcomp && $(SUBDIR_MMAKE) tags
 
 .PHONY: tags_browser
 tags_browser:
@@ -253,7 +272,8 @@ tags_deep_profiler:
 # Remove from each of the listed directories mmc-generated files that don't
 # belong there.
 cleanint:
-	for dir in analysis browser compiler deep_profiler library profiler; \
+	for dir in library mdbcomp browser analysis compiler \
+		profiler deep_profiler; \
 	do \
 		echo Looking for inappropriate files in the $$dir directory: ; \
 		( cd $$dir && ../tools/cleanint > .cleanint ) ; \
@@ -321,9 +341,12 @@ tar: $(GENERATED_DOCS)
 	+cd runtime && $(SUBDIR_MMAKE) cs $(RT_LIB_NAME).init
 	+cd library && $(SUBDIR_MMAKE) depend
 	+cd library && $(SUBDIR_MMAKE) all-ints cs $(STD_LIB_NAME).init tags
+	+cd mdbcomp && $(SUBDIR_MMAKE) depend
+	+cd mdbcomp && $(SUBDIR_MMAKE) all-ints cs \
+		$(MDBCOMP_LIB_NAME).init tags
 	+cd browser && $(SUBDIR_MMAKE) depend
 	+cd browser && $(SUBDIR_MMAKE) all-ints cs \
-		$(BROWSER_LIB_NAME).init $(MDBCOMP_LIB_NAME).init tags
+		$(BROWSER_LIB_NAME).init tags
 	+cd trace && $(SUBDIR_MMAKE) cs
 	+cd analysis && $(SUBDIR_MMAKE) depend
 	+cd analysis && $(SUBDIR_MMAKE) all-ints cs tags
@@ -425,10 +448,10 @@ install: install_main install_grades
 .PHONY: install_main
 install_main: all \
 		install_scripts install_util install_runtime install_boehm_gc \
-  		install_library install_browser install_trace \
+		install_library install_mdbcomp install_browser install_trace \
 		install_compiler install_profiler install_deep_profiler \
 		install_doc install_config
- 
+
 .PHONY: install_scripts
 install_scripts: scripts
 	+cd scripts && $(SUBDIR_MMAKE) install
@@ -460,6 +483,10 @@ install_boehm_gc: boehm_gc
 install_library: dep_library library
 	+cd library && $(SUBDIR_MMAKE) install
 
+.PHONY: install_mdbcomp
+install_mdbcomp: dep_mdbcomp mdbcomp
+	+cd mdbcomp && $(SUBDIR_MMAKE) install
+
 .PHONY: install_browser
 install_browser: dep_browser browser
 	+cd browser && $(SUBDIR_MMAKE) install
@@ -480,20 +507,11 @@ install_profiler: profiler
 install_deep_profiler: deep_profiler
 	+cd deep_profiler && $(SUBDIR_MMAKE) install
 
+# LIBGRADE_SUFFIXES = .m .int3 .date3 .int2 .int .date .opt .optdate \
+#	.trans_opt .trans_opt_date .d .mh .mih .c_date  .c .o .pic_o
+
 .PHONY: install_grades
-install_grades: scripts
-	for dir in boehm_gc runtime trace; do \
-	    ( cd $$dir; rm -rf tmp_dir; mkdir tmp_dir; \
-		mv -f *.$O *.pic_o *.$A *.so tmp_dir; true ); \
-	done
-	for dir in library browser; do \
-	    ( cd $$dir && rm -rf tmp_dir && mkdir tmp_dir && \
-		for ext in $(GRADE_SUBDIR_EXTS); do \
-		    mv -f *.$$ext Mercury/$${ext}s/*.$$ext tmp_dir; \
-		done; \
-		mv -f $(deps_subdir)*.dep $(deps_subdir)*.dv *.$O \
-			Mercury/os/*.$O *.$A *.so tmp_dir; true ); \
-	done
+install_grades: all
 	#
 	# Use the newly installed compiler to build the libraries
 	# in various different grades.  We need to override MC=mmc
@@ -501,48 +519,44 @@ install_grades: scripts
 	# runs the newly installed compiler, rather than using the
 	# bootstrap compiler.
 	#
-	+for grade in x $(LIBGRADES); do \
-	    if [ "$$grade" != "x" -a "$$grade" != "$(GRADE)" ]; then \
-	    	gc_grade=`scripts/ml --grade $$grade --print-gc-grade`; \
-	        ( cd boehm_gc && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade GC_GRADE=$$gc_grade \
-		  	install_lib ) && \
-		( cd runtime && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade install_lib ) && \
-		( cd library && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade depend && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade install_library ) && \
-		( cd browser && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade depend && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade install_library ) && \
-		( cd trace && \
-		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade install_lib ) && \
-		for dir in boehm_gc runtime trace; do \
-			( cd $$dir && rm -f *.$O *.pic_o *.$A *.so ); \
-		done && \
-		for dir in library browser; do \
-		   ( cd $$dir && \
-		   	for ext in $(GRADE_SUBDIR_EXTS); do \
-				rm -f *.$$ext Mercury/$${ext}s/*.$$ext; \
-			done && \
-			rm -f $(deps_subdir)*.dep $(deps_subdir)*.dv *.$O \
-				Mercury/os/*.$O *.$A *.so ); \
-		done \
-		|| { scripts/mercury_cleanup_install; exit 1; }; \
-	    fi; \
+	/bin/rm -fr tmp_dir
+	scripts/prepare_tmp_dir_fixed_part
+	+for grade in x $(LIBGRADES); do				\
+	    if [ "$$grade" != "x" -a "$$grade" != "$(GRADE)" ]; then	\
+		gc_grade=`scripts/ml --grade $$grade --print-gc-grade`;	\
+		TWS=`/bin/pwd`/tmp_dir;					\
+		scripts/prepare_tmp_dir_grade_part;			\
+	        ( cd tmp_dir/boehm_gc &&				\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade			\
+			WORKSPACE=$$TWS GC_GRADE=$$gc_grade		\
+			install_lib ) &&				\
+		( cd tmp_dir/runtime &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			install_lib ) &&				\
+		( cd tmp_dir/library &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			depend &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			install_library ) &&				\
+		( cd tmp_dir/mdbcomp &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			depend &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			install_library ) &&				\
+		( cd tmp_dir/browser &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			depend &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			install_library ) &&				\
+		( cd tmp_dir/trace &&					\
+		  $(SUBDIR_MMAKE) MC=mmc GRADE=$$grade WORKSPACE=$$TWS	\
+			install_lib ) &&				\
+		true ||							\
+		{ echo "To clean up from failed install, remove tmp_dir"; \
+		  exit 1; };						\
+	    fi;								\
 	done
-	for dir in boehm_gc runtime trace; do \
-	    ( cd $$dir && { mv tmp_dir/* . ; rmdir tmp_dir; true; } ); \
-	done
-	for dir in library browser; do \
-	    ( cd $$dir && { \
-		for ext in $(GRADE_SUBDIR_EXTS); do \
-		    [ -d Mercury/$${ext}s ] && \
-		    	mv tmp_dir/*.$$ext Mercury/$${ext}s; \
-		done; \
-		mv tmp_dir/*.dep tmp_dir/*.dv $(deps_subdir).; \
-	    	mv tmp_dir/* . ; rmdir tmp_dir; true; } ); \
-	done
+	if test ! -f .leave_tmp_dir; then rm -fr tmp_dir; fi
 
 .PHONY: install_split_library
 install_split_library: scripts dep_library
@@ -593,6 +607,10 @@ touch_files:
 	touch library/*.optdate
 	chmod +w library/*.dep
 	touch library/*.dep
+	touch mdbcomp/*.date*
+	touch mdbcomp/*.optdate
+	chmod +w mdbcomp/*.dep
+	touch mdbcomp/*.dep
 	touch browser/*.date*
 	touch browser/*.optdate
 	chmod +w browser/*.dep
@@ -614,6 +632,7 @@ touch_files:
 	touch boehm_gc/*.c
 	touch runtime/*.c
 	touch library/*.c
+	touch mdbcomp/*.c
 	touch browser/*.c
 	touch trace/*.c
 	touch compiler/*.c
@@ -646,7 +665,8 @@ clean: clean_subdirs clean_tests
 
 .PHONY: clean_subdirs
 clean_subdirs:
-	rm -rf runtime/tmp_dir library/tmp_dir browser/tmp_dir trace/tmp_dir
+	rm -rf runtime/tmp_dir library/tmp_dir mdbcomp/tmp_dir \
+		browser/tmp_dir trace/tmp_dir
 	+for dir in $(SUBDIRS); do \
 		if [ "$$dir" = scripts ]; then continue; fi; \
 		(cd $$dir; $(SUBDIR_MMAKE) clean) \
diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -69,7 +69,7 @@ Options:
 		check to have left a working stage 2 directory.
 	--no-check-namespace
 		Don't build the check_namespace targets in the runtime,
-		trace, browser and library directories.
+		trace, browser, mdbcomp and library directories.
 	-t-, --no-test-suite
 		By default, bootcheck will also run the test quite.
 		This option prevents that.
@@ -569,12 +569,18 @@ then
 		$LN_S $root/library/$STD_LIB_NAME.init .
 		$LN_S $root/library/RESERVED_MACRO_NAMES .
 		cd $root/$stage2dir
+		mkdir mdbcomp
+		cd mdbcomp
+		$LN_S $root/mdbcomp/*.m .
+		cp $root/mdbcomp/Mmake* $root/mdbcomp/Mercury.options .
+		$LN_S $root/mdbcomp/$MDCOMP_LIB_NAME.init .
+		$LN_S $root/mdbcomp/RESERVED_MACRO_NAMES .
+		cd $root/$stage2dir
 		mkdir browser
 		cd browser
 		$LN_S $root/browser/*.m .
 		cp $root/browser/Mmake* $root/browser/Mercury.options .
 		$LN_S $root/browser/$BROWSER_LIB_NAME.init .
-		$LN_S $root/browser/$MDCOMP_LIB_NAME.init .
 		$LN_S $root/browser/RESERVED_MACRO_NAMES .
 		cd $root/$stage2dir
 		mkdir analysis
@@ -686,6 +692,11 @@ then
 			/bin/rm -f Mmake.params
 			cp $root/Mmake.stage.params Mmake.params
 		fi
+		if test -f $root/Mmake.stage.mdbcomp.params
+		then
+			/bin/rm -f mdbcomp/Mmake.mdbcomp.params
+			cp $root/Mmake.stage.mdbcomp.params mdbcomp/Mmake.mdbcomp.params
+		fi
 		if test -f $root/Mmake.stage.browser.params
 		then
 			/bin/rm -f browser/Mmake.browser.params
@@ -743,8 +754,8 @@ then
 		fi
 
 		if (cd $stage2dir && \
-			$MMAKE $mmake_opts dep_library dep_browser \
-			dep_analysis dep_compiler dep_profiler \
+			$MMAKE $mmake_opts dep_library dep_mdbcomp \
+			dep_browser dep_analysis dep_compiler dep_profiler \
 			dep_deep_profiler)
 		then
 			echo "building of stage 2 dependencies successful"
@@ -775,6 +786,15 @@ then
 
 			mv $stage2dir/library/$STD_LIB_NAME.split.a \
 				$stage2dir/library/$STD_LIB_NAME.a
+		fi
+
+		if (cd $stage2dir/mdbcomp && \
+			$MMAKE $mmake_opts $jfactor library)
+		then
+			echo "building of stage 2 mdbcomp successful"
+		else
+			echo "building of stage 2 mdbcomp not successful"
+			exit 1
 		fi
 
 		if (cd $stage2dir/browser && \
@@ -859,6 +879,11 @@ then
 			echo '** mmake check_namespace failed in library!'
 			check_namespace_status=1
 		}
+		cd $root/$stage2dir/mdbcomp
+		mmake $mmake_opts check_namespace || {
+			echo '** mmake check_namespace failed in mdbcomp!'
+			check_namespace_status=1
+		}
 		cd $root/$stage2dir/browser
 		mmake $mmake_opts check_namespace || {
 			echo '** mmake check_namespace failed in browser!'
@@ -879,7 +904,7 @@ then
 	then
 		true
 	else
-		libdirs="library browser"
+		libdirs="library mdbcomp browser"
 		if $copy_profiler
 		then
 			profdirs="profiler deep_profiler"
@@ -900,7 +925,7 @@ then
 			/bin/rm -f *.o *.pic_o
 		done
 
-		for cleandir in runtime trace library browser
+		for cleandir in runtime trace library mdbcomp browser
 		do
 			cd $root/$stage2dir/$cleandir
 			mmake clean_check
@@ -954,12 +979,17 @@ then
 	cp $root/library/Mmake* $root/library/Mercury.options .
 	$LN_S $root/library/$STD_LIB_NAME.init .
 	cd $root/$stage3dir
+	mkdir mdbcomp
+	cd mdbcomp
+	$LN_S $root/mdbcomp/*.m .
+	cp $root/mdbcomp/Mmake* $root/mdbcomp/Mercury.options .
+	$LN_S $root/mdbcomp/$MDBCOMP_LIB_NAME.init .
+	cd $root/$stage3dir
 	mkdir browser
 	cd browser
 	$LN_S $root/browser/*.m .
 	cp $root/browser/Mmake* $root/browser/Mercury.options .
 	$LN_S $root/browser/$BROWSER_LIB_NAME.init .
-	$LN_S $root/browser/$MDBCOMP_LIB_NAME.init .
 	cd $root/$stage3dir
 	mkdir analysis
 	cd analysis
@@ -1010,8 +1040,8 @@ then
 		cp /dev/null "$type_stats"
 	fi
 
-	if (cd $stage3dir && $MMAKE $mmake_opts dep_library dep_browser \
-		dep_analysis dep_compiler)
+	if (cd $stage3dir && $MMAKE $mmake_opts dep_library dep_mdbcomp \
+		dep_browser dep_analysis dep_compiler)
 	then
 		echo "building of stage 3 dependencies successful"
 	else
@@ -1051,6 +1081,23 @@ then
 	else
 		find $root/$stage2dir/compiler -name "*.o" -print |
 		xargs /bin/rm -f
+	fi
+
+	if (cd $stage3dir/mdbcomp && $MMAKE $mmake_opts $jfactor ${target_ext}s)
+	then
+		echo "building of stage 3 mdbcomp successful"
+	else
+		echo "building of stage 3 mdbcomp initially not successful"
+		df .
+		# try again, in case the failure cause was transient
+		if (cd $stage3dir/mdbcomp && \
+			$MMAKE $mmake_opts $jfactor ${target_ext}s)
+		then
+			echo "building of stage 3 mdbcomp successful"
+		else
+			echo "building of stage 3 mdbcomp not successful"
+			exit 1
+		fi
 	fi
 
 	if (cd $stage3dir/browser && $MMAKE $mmake_opts $jfactor ${target_ext}s)
@@ -1123,7 +1170,7 @@ then
 		exec > "$outfile"	# redirect stdout to $outfile
 	fi
 
-	for dir in library browser analysis compiler; do
+	for dir in library mdbcomp browser analysis compiler; do
 		# `mmake cs' in the compiler directory doesn't build
 		# `top_level_init.c', so we only compare the `.c'
 		# files present in the stage 3 directory.
@@ -1162,6 +1209,7 @@ then
 				# files to be reconstructed
 				# relatively quickly.
 				gzip $root/$stage2dir/library/*.c
+				gzip $root/$stage2dir/mdbcomp/*.c
 				gzip $root/$stage2dir/browser/*.c
 				gzip $root/$stage2dir/compiler/*.c
 				;;
