Check the trace directory for namespace cleanliness.
Estimated hours taken: 3

Check the trace directory for namespace cleanliness.

Mmake.common.in:
runtime/Mmakefile:
	Move the rules for checking namespace violations from runtime/Mmakefile
	to Mmake.common.

trace/Mmakefile:
	Add entries for checking the name-space cleanliness of the trace
	directory, using the rules now in Mmake.common. These entries follow
	the same rules as the ones in the runtime directory. Note that the
	the header files of the trace directory must be allowed to define
	all the macros that the runtime directory's header files can, since
	some trace directory header files include header files from the runtime
	directory.

trace/*.h:
	Make these header files self-contained.

tools/bootcheck:
	Check the trace directory for namespace cleanliness as well as the
	runtime directory.

diff --git a/Mmake.common.in b/Mmake.common.in
--- a/Mmake.common.in
+++ b/Mmake.common.in
@@ -237,3 +237,56 @@ BOEHMGC_MAKEFILE=@BOEHMGC_MAKEFILE@
 -include $(MERCURY_DIR)/Mmake.params
 
 #-----------------------------------------------------------------------------#
+
+# This rule checks that object files are properly namespace-clean, with
+# regard to the global symbols that they define.
+# For an object file foo.o, it produces a file foo.o.obj_check that
+# contains a list of all the globals defined by that object that
+# do not start with `MR_', `mercury_', or `entry_'.
+
+%.obj_check: %
+	nm -g $< | awk '$$1 != "U" { print $$3; }' | \
+		grep -v -e '^_entry' -e '^MR_' -e '^mercury_' | \
+		sort -u > $@
+	@if cmp -s /dev/null $@; then \
+		true; \
+	else \
+		echo "** Global symbols in user namespace:"; \
+		cat $@; \
+		echo "(You may need to add MR_ prefixes to these names.)"; \
+		exit 1; \
+	fi
+
+# This rule helps to check that header files is self-contained, i.e. that each
+# header file foo.h includes any other header files that define types
+# used by foo.h. It creates a foo_check.c file that contains only a single
+# `#include' statement that includes foo.h; compiling foo_check.c will fail
+# if foo.h is not self-contained.
+
+%_check.c : %.h
+	echo "#include \"$*.h\"" > $*_check.c
+
+# This rule checks whether a header file defines any macros it shouldn't.
+# It generates the list of macros defined in the header file, and filters this
+# list through a command that is intended to filter out all references to macro
+# names that are all right. Each directory that uses this rule must set
+# the HEADER_CLEAN_FILTER make variable to contain this command.
+
+AWK = awk
+%_check.macros: %.h %_check.c
+	-$(MGNUC) $(ALL_GRADEFLAGS) $(ALL_MGNUCFLAGS) \
+		-DMERCURY_BOOTSTRAP_H \
+		-E $*_check.c \
+		-nostdinc -dN \
+		2> /dev/null | $(AWK) '/^#define/ { print $$2; }' | \
+		$(HEADER_CLEAN_FILTER) | sort -u > $@
+	@if cmp -s /dev/null $@; then \
+		true; \
+	else \
+		echo "** Macro name(s) in user namespace:"; \
+		cat $@; \
+		echo "(You may need to add a distinguishing prefix to these names.)"; \
+		exit 1; \
+	fi
+
+#-----------------------------------------------------------------------------#
diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -58,7 +58,8 @@ Options:
 		the extras only. This option requires a previous bootstrap
 		check to have left a working stage 2 directory.
 	--no-check-namespace
-		Don't build the check_namespace target in the runtime.
+		Don't build the check_namespace targets in the runtime
+		and trace directories.
 	-t, --no-test-suite
 		By default, bootcheck will also run the test quite.
 		This option prevents that.
@@ -869,6 +870,16 @@ check_namespace_status=0
 if $check_namespace
 then
 	cd $root/${stage2_insert}runtime
+	mmake $mmake_opts check_namespace || {
+		echo '** mmake check_namespace failed!'
+		# XXX Currently we just report the errors;
+		#     we don't yet actually return a non-zero status.
+		#     That's why the line below is commented out.
+		#     This is a transition measure until we're sure
+		#     that everything really is namespace-clean.
+		# check_namespace_status=1
+	}
+	cd $root/${stage2_insert}trace
 	mmake $mmake_opts check_namespace || {
 		echo '** mmake check_namespace failed!'
 		# XXX Currently we just report the errors;
