Update the style of recompilation test scripts.
tests/recompilation/test_functions:
tests/recompilation/two_module_test:
    Update these shell scripts to our current coding style.

diff --git a/tests/recompilation/two_module_test b/tests/recompilation/two_module_test
--- a/tests/recompilation/two_module_test
+++ b/tests/recompilation/two_module_test
@@ -1,14 +1,15 @@
 #!/bin/sh
+# vim: ts=4 sw=4 expandtab ft=sh
 # Run a test which compiles a two module test case,
 # changes one of the modules, then tries to recompile.
 #
 
 . ./test_functions
 
-if [ $# != 3 ]
+if test "$#" != 3
 then
-	echo "** usage: two_module_test test_should_fail module1 module2"
-	exit 1
+    echo "** usage: two_module_test test_should_fail module1 module2"
+    exit 1
 fi
 
 test_should_fail=$1
@@ -16,11 +17,10 @@ module1=$2
 module2=$3
 
 test_module "$module1" "$module2"
-mmake_depend 
+mmake_depend
 mmake_test 1 false
 update_module "$module2" 2
-mmake_test 2 $test_should_fail
+mmake_test 2 "$test_should_fail"
 check_err_file "$module1" 2
 check_err_file "$module2" 2
 cleanup_test
-
