Merged in the changes on the main trunk between
Estimated hours taken: 12

Merged in the changes on the main trunk between
trunk_snapshot_19990824125054 and trunk_snapshot_19991221190219, plus
changes required to update the usual RTTI stuff, etc.

diff --git a/library/Mmakefile b/library/Mmakefile
--- a/library/Mmakefile
+++ b/library/Mmakefile
@@ -62,8 +62,8 @@ MCOI	=	$(M_ENV) $(MC) --make-opt-int $(INTERMODULE_OPTS) \
 			$(ENABLE_TERM_OPTS)
 MCTOI	=	$(M_ENV) $(MC) --make-trans-opt $(INTERMODULE_OPTS) \
 			$(ENABLE_TERM_OPTS)
-MCG	=	$(M_ENV) $(MC) --compile-to-c $(INTERMODULE_OPTS) \
-			$(CHECK_TERM_OPTS)
+MCG	=	$(M_ENV) $(MC) --compile-to-c --trace minimum \
+			$(INTERMODULE_OPTS) $(CHECK_TERM_OPTS)
 MCS	=	$(M_ENV) $(MC) --split-c-files -c --cflags "$(ALL_CFLAGS)" \
 			$(INTERMODULE_OPTS) $(CHECK_TERM_OPTS)
 MGNUC	=	$(M_ENV) $(SCRIPTS_DIR)/mgnuc
@@ -214,7 +214,7 @@ $(os_subdir)std_util.pic_o \
 
 #-----------------------------------------------------------------------------#
 
-realclean:
+realclean_local:
 	rm -f lib$(STD_LIB_NAME).a lib$(STD_LIB_NAME).so $(STD_LIB_NAME).init
 	rm -f tags
 
@@ -262,9 +262,16 @@ install_ints: $(library.ints) $(library.int3s) \
 		fi; \
 	done
 	# The following is needed to support the `--use-subdirs' option
-	for dir in ints int2s int3s opts trans_opts; do \
+	# We try using `ln -s', but if that fails, then we just use `cp'.
+	for ext in int int2 int3 opt trans_opt; do \
+		dir=$${ext}s; \
 		rm -f $(INSTALL_INT_DIR)/Mercury/$$dir; \
-		ln -s .. $(INSTALL_INT_DIR)/Mercury/$$dir; \
+		ln -s .. $(INSTALL_INT_DIR)/Mercury/$$dir || { \
+			[ -d $(INSTALL_INT_DIR)/Mercury/$$dir ] || \
+				mkdir -p $(INSTALL_INT_DIR)/Mercury/$$dir; \
+			cp $(INSTALL_INT_DIR)/*.$$ext \
+				$(INSTALL_INT_DIR)/Mercury/$$dir; \
+		} || exit 1; \
 	done
 
 .PHONY: install_init
diff --git a/scripts/ml.in b/scripts/ml.in
--- a/scripts/ml.in
+++ b/scripts/ml.in
@@ -14,6 +14,70 @@
 #
 # Environment variables: MERCURY_C_LIB_DIR, MERCURY_DEFAULT_GRADE, ...
 
+FULLARCH=@FULLARCH@
+NONSHARED_LIB_DIR=${MERCURY_NONSHARED_LIB_DIR=@NONSHARED_LIB_DIR@}
+DEFAULT_LIBDIR=@LIBDIR@/lib
+LIBDIR=${MERCURY_C_LIB_DIR=$DEFAULT_LIBDIR}
+DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
+# DEMANGLER=${MERCURY_DEMANGLER=@LIBDIR@/bin/@FULLARCH@/mdemangle}
+DEMANGLER=${MERCURY_DEMANGLER=mdemangle}
+CC=${MERCURY_C_COMPILER="@CC@"}
+MKFIFO=${MERCURY_MKFIFO="@MKFIFO@"}
+ERROR_UNDEFINED="@ERROR_UNDEFINED@"
+ALLOW_UNDEFINED="@ALLOW_UNDEFINED@"
+EXE_RPATH_OPT=${MERCURY_EXE_RPATH_OPT="@EXE_RPATH_OPT@"}
+EXE_RPATH_SEP=${MERCURY_EXE_RPATH_SEP="@EXE_RPATH_SEP@"}
+EXT_FOR_SHARED_LIB=${MERCURY_EXT_FOR_SHARED_LIB="@EXT_FOR_SHARED_LIB@"}
+LINK_SHARED_OBJ=${MERCURY_LINK_SHARED_OBJ="@LINK_SHARED_OBJ_SH@"}
+SHLIB_RPATH_OPT=${MERCURY_SHLIB_RPATH_OPT="@SHLIB_RPATH_OPT@"}
+SHLIB_RPATH_SEP=${MERCURY_SHLIB_RPATH_SEP="@SHLIB_RPATH_SEP@"}
+SHARED_LIBS=${MERCURY_SHARED_LIBS="@SHARED_LIBS@"}
+TMPDIR=${TMPDIR=/tmp}
+
+# On some systems (Solaris for exemple), we need libraries to be able to 
+# use sockets. The name of the needed libraries is determined by autoconf
+# and passed through this variable.
+SOCKET_LIBRARY="@SOCKET_LIBRARY@"
+NSL_LIBRARY="@NSL_LIBRARY@"
+
+# Likewise for -ldl (libdl.so), which is often needed for dlopen() etc.
+DL_LIBRARY="@DL_LIBRARY@"
+
+# Likewise for -lreadline -l{termcap,curses,ncurses}
+READLINE_LIBRARIES="@READLINE_LIBRARIES@"
+
+# If you change these, you will also need to change Mmake.common.in,
+# scripts/c2init.in, tools/bootcheck, tools/binary, tools/binary_step
+# and tools/linear.
+RT_LIB_NAME=mer_rt
+STD_LIB_NAME=mer_std
+TRACE_LIB_NAME=mer_trace
+BROWSER_LIB_NAME=mer_browser
+
+verbose=false
+allow_undefined=false
+trace=false
+readline=true
+case $FULLARCH in
+	*-win95|*-winnt|*-win32|*-cygwin32|*-cygwin)
+		# `gcc -s' is broken in gnu-win32
+		strip=false
+		;;
+	*)
+		strip=true
+		;;
+esac
+mercury_libs=default
+all_libs=default
+demangle=true
+MAYBE_STATIC_OPT=""
+make_shared_lib=false
+leave_shlib_dirs_relative=false
+user_shlib_dirs=""
+
+# include the file `init_grade_options.sh-subr'
+@INIT_GRADE_OPTIONS@
+
 Help="\
 Name: ml - Mercury Linker
 Usage: ml [<ml options>] [-- <gcc options>] files...
@@ -84,87 +148,7 @@ Debugging options:
 	-g, --c-debug, --no-strip
 		Do not strip C debugging information.
 
-Grade options:
-	-s <grade>, --grade <grade>
-	--asm-labels
-	--gcc-non-local-gotos
-	--gcc-global-registers
-	--gc {conservative, accurate, none}
-	-p, --profiling
-	--profile-calls
-	--profile-time
-	--profile-memory
-	--debug
-	--low-level-debug
-	--use-trail
-	--reserve-tag
-	--use-solve-equal
-	--use-init
-	--pic-reg
-		See the documentation in the \"Invocation\" section
-		of the Mercury User's Guide."
-
-FULLARCH=@FULLARCH@
-NONSHARED_LIB_DIR=${MERCURY_NONSHARED_LIB_DIR=@NONSHARED_LIB_DIR@}
-DEFAULT_LIBDIR=@LIBDIR@/lib
-LIBDIR=${MERCURY_C_LIB_DIR=$DEFAULT_LIBDIR}
-DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
-# DEMANGLER=${MERCURY_DEMANGLER=@LIBDIR@/bin/@FULLARCH@/mdemangle}
-DEMANGLER=${MERCURY_DEMANGLER=mdemangle}
-CC=${MERCURY_C_COMPILER="@CC@"}
-MKFIFO=${MERCURY_MKFIFO="@MKFIFO@"}
-ERROR_UNDEFINED="@ERROR_UNDEFINED@"
-ALLOW_UNDEFINED="@ALLOW_UNDEFINED@"
-EXE_RPATH_OPT=${MERCURY_EXE_RPATH_OPT="@EXE_RPATH_OPT@"}
-EXE_RPATH_SEP=${MERCURY_EXE_RPATH_SEP="@EXE_RPATH_SEP@"}
-EXT_FOR_SHARED_LIB=${MERCURY_EXT_FOR_SHARED_LIB="@EXT_FOR_SHARED_LIB@"}
-LINK_SHARED_OBJ=${MERCURY_LINK_SHARED_OBJ="@LINK_SHARED_OBJ@"}
-SHLIB_RPATH_OPT=${MERCURY_SHLIB_RPATH_OPT="@SHLIB_RPATH_OPT@"}
-SHLIB_RPATH_SEP=${MERCURY_SHLIB_RPATH_SEP="@SHLIB_RPATH_SEP@"}
-SHARED_LIBS=${MERCURY_SHARED_LIBS="@SHARED_LIBS@"}
-
-# On some systems (Solaris for exemple), we need libraries to be able to 
-# use sockets. The name of the needed libraries is determined by autoconf
-# and passed through this variable.
-SOCKET_LIBRARY="@SOCKET_LIBRARY@"
-
-# Likewise for -ldl (libdl.so), which is often needed for dlopen() etc.
-DL_LIBRARY="@DL_LIBRARY@"
-
-# Likewise for -lreadline -l{termcap,curses,ncurses}
-READLINE_LIBRARIES="@READLINE_LIBRARIES@"
-
-# If you change these, you will also need to change Mmake.common.in,
-# scripts/c2init.in, tools/bootcheck, tools/binary, tools/binary_step
-# and tools/linear.
-RT_LIB_NAME=mer_rt
-STD_LIB_NAME=mer_std
-TRACE_LIB_NAME=mer_trace
-BROWSER_LIB_NAME=mer_browser
-
-verbose=false
-allow_undefined=false
-trace=false
-readline=true
-case $FULLARCH in
-	*-win95|*-winnt|*-win32|*-cygwin32|*-cygwin)
-		# `gcc -s' is broken in gnu-win32
-		strip=false
-		;;
-	*)
-		strip=true
-		;;
-esac
-mercury_libs=default
-all_libs=default
-demangle=true
-MAYBE_STATIC_OPT=""
-make_shared_lib=false
-leave_shlib_dirs_relative=false
-user_shlib_dirs=""
-
-# include the file `init_grade_options.sh-subr'
-@INIT_GRADE_OPTIONS@
+$grade_usage"
 
 while : ; do
     case "$1" in
@@ -353,7 +337,7 @@ case $all_libs in static)
 			# boehm_gc/dyn_load.c.
 			# (We might eventually need similar treatment
 			# for other OSs too)
-			MAYBE_STATIC_OPT="-static -Wl,-defsym,_DYNAMIC=0"
+			MAYBE_STATIC_OPT="-static -Wl-defsym -Wl_DYNAMIC=0"
 			;;
 		*)
 			MAYBE_STATIC_OPT=-static
@@ -374,6 +358,10 @@ esac
 case $asm_labels in
 	true)		GRADE="asm_$GRADE" ;;
 	false)		;;
+esac
+case $thread_safe in
+	true)	GRADE="$GRADE.par" ;;
+	false)	;;
 esac
 case $gc_method in
 	conservative)	GRADE="$GRADE.gc" ;;
@@ -408,15 +396,21 @@ case $use_init in
 	true)		GRADE="$GRADE.init" ;;
 	false)		;;
 esac
+case $use_minimal_model in
+	true)	GRADE="$GRADE.mm" ;;
+	false)	;;
+esac
+# We ignore the value of $picreg in computing the name of the grade
+# that we will use as a directory name below.
+# case $picreg in
+# 	true)	GRADE="$GRADE.picreg" ;;
+# 	false)	;;
+# esac
 case $stack_trace,$require_tracing in
 	true,true)	GRADE="$GRADE.debug" ;;
 	false,true)	GRADE="$GRADE.trace" ;;
 	true,false)	GRADE="$GRADE.strce" ;;
 	false,false)	;;
-esac
-case $thread_safe in
-	true)	GRADE="$GRADE.par" ;;
-	false)	;;
 esac
 
 case "$GRADE" in
@@ -442,7 +436,7 @@ esac
 
 case $trace in
 	true)	TRACE_LIBS="-l$TRACE_LIB_NAME -l$BROWSER_LIB_NAME"
-		TRACE_LIBS_SYSTEM="$SOCKET_LIBRARY $DL_LIBRARY \
+		TRACE_LIBS_SYSTEM="$SOCKET_LIBRARY $NSL_LIBRARY $DL_LIBRARY \
 			$READLINE_LIBRARIES"
 		TRACE_STATIC_LIBS="\
 			$LIBDIR/$GRADE/$FULLARCH/lib$TRACE_LIB_NAME.a \
@@ -605,33 +599,50 @@ case $demangle in
 		# create the pipe, making sure we remove it if interrupted
 	old_umask=`umask`
 	umask 022
-	ML_TMPDIR=/tmp/ml$$
-	PIPE=$ML_TMPDIR/pipe
-	trap 'rmdir $ML_TMPDIR >/dev/null 2>&1; exit 1' 1 2 3 13 15 
-	if mkdir $ML_TMPDIR ; then
-		true
-	else
-		echo "Unable to create temporary pipe" 1>&2
-		exit 1
-	fi
+	try=0
+	until 
+		ML_TMPDIR=$TMPDIR/ml$$
+		PIPE=$ML_TMPDIR/pipe
+		trap 'rmdir $ML_TMPDIR >/dev/null 2>&1; exit 1' 1 2 3 13 15 
+		mkdir $ML_TMPDIR
+	do
+		try="`expr $try + 1`"
+		# give up after 20 tries
+		case "$try" in 20)
+			echo "ml: unable to create temporary directory" \
+				"for pipe" 1>&2
+			exit 1
+		esac
+	done
 	trap 'rm -rf $ML_TMPDIR; exit 1' 1 2 3 13 15 
 	umask $old_umask
 	$MKFIFO $PIPE
 		# execute the demangler in the background, with stdin 
 		# coming from the pipe and with stdout redirected to stderr
-	exec $DEMANGLER 1>&2 < $PIPE &
-		# redirect our stdout and stderr into the pipe
-	exec >$PIPE 2>&1
-		# now we can remove the pipe; since is an open file, it will
-		# stay around until $CC and $DEMANGLER exit
-	rm -rf $ML_TMPDIR
-		# finally execute $CC; stdout & stderr will
+	exec $DEMANGLER --explain-link-errors 1>&2 < $PIPE &
+		# execute $CC with stdout & stderr redirected to
 		# go via the pipe to $DEMANGLER and then to stderr
+	case $# in
+		0) $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
+			$LIBDIR_OPTS $RPATH_OPT_LIST $LIBS >$PIPE 2>&1 ;;
+
+		*) $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
+			$LIBDIR_OPTS $RPATH_OPT_LIST "$@" $LIBS >$PIPE 2>&1 ;;
+	esac
+	linker_status=$?
+		# now we can remove the pipe; since is an open file, it will
+		# stay around until $DEMANGLER exits
+	rm -rf $ML_TMPDIR
+		# wait for the demangler to exit before exiting ourselves
+	wait
+	exit $linker_status
 	;;
-esac
-case $# in
-	0) exec $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
-		$LIBDIR_OPTS $RPATH_OPT_LIST $LIBS ;;
-	*) exec $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
-		$LIBDIR_OPTS $RPATH_OPT_LIST "$@" $LIBS ;;
+false)
+	case $# in
+		0) exec $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
+			$LIBDIR_OPTS $RPATH_OPT_LIST $LIBS ;;
+		*) exec $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT $ARCH_OPTS \
+			$LIBDIR_OPTS $RPATH_OPT_LIST "$@" $LIBS ;;
+	esac
+	;;
 esac
diff --git a/scripts/mmake.in b/scripts/mmake.in
--- a/scripts/mmake.in
+++ b/scripts/mmake.in
@@ -68,6 +68,7 @@ MMAKE_RULES=${MMAKE_RULES=$MMAKE_DIR/Mmake.rules}
 MERCURY_INT_DIR=${MERCURY_INT_DIR=@LIBDIR@/ints}
 MERCURY_DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
 MKTEMP=@MKTEMP@
+TMPDIR=${TMPDIR=/tmp}
 
 MMAKE=$0
 verbose=false
@@ -181,23 +182,29 @@ else
 	case "$MKTEMP" in
 		"") 	old_umask=`umask`
 			umask 022
-			mmake_tmpdir=/tmp/mmake$$
-			tmp=$mmake_tmpdir/mmake
-			trap 'rmdir $mmake_tmpdir >/dev/null 2>&1; exit 1' \
-				1 2 3 13 15
-			if mkdir $mmake_tmpdir ; then
-				true
-			else
-				echo "Unable to create temporary makefile" 1>&2
-				exit 1
-			fi
+			try=0
+			until
+				mmake_tmpdir=$TMPDIR/mmake$$-$try
+				tmp=$mmake_tmpdir/mmake
+				trap 'rmdir $mmake_tmpdir >/dev/null 2>&1; exit 1' \
+					1 2 3 13 15
+				mkdir $mmake_tmpdir
+			do
+				try=`expr $try + 1`
+				# give up after 20 tries
+				case $try in 20)
+					echo "mmake: unable to create directory" \
+						"for temporary makefile" 1>&2
+					exit 1
+				esac
+			done
 			trap 'status=$?; rm -rf $mmake_tmpdir; exit $status' \
 				0 1 2 3 13 15
 			umask $old_umask
 			;;
 		*)
 			# mktemp should give its own error message.
-			tmp=`$MKTEMP /tmp/mmake.XXXXXX` || exit 1
+			tmp=`$MKTEMP $TMPDIR/mmake.XXXXXX` || exit 1
 			trap 'status=$?; rm -f $tmp; exit $status' 0 1 2 3 13 15
 			;;
 	esac
diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -202,6 +202,16 @@ fi
 MMAKE_USE_SUBDIRS=$use_subdirs
 export MMAKE_USE_SUBDIRS
 
+#-----------------------------------------------------------------------------#
+
+# on hg, the file system we're using does not support links
+case `hostname` in
+	hg*)	LN="cp -r"; LN_S="cp -r" ;;
+	*)	LN="ln"; LN_S="ln -s" ;;
+esac
+
+#-----------------------------------------------------------------------------#
+
 # Turn off the debugger, since accidentally leaving it on will result
 # in user interaction every time we invoke any version of the compiler
 # that was compiled with tracing. This has happened to me accidentally 
@@ -289,88 +299,88 @@ then
 	# This is needed to cope with small limits
 	# on the size of argument vectors.
 
-	ln -s $root/compiler/[a-h]*.m .
-	ln -s $root/compiler/[i-o]*.m .
-	ln -s $root/compiler/[p-s]*.m .
-	ln -s $root/compiler/[t-z]*.m .
-	ln -s $root/compiler/*.pp .	
+	$LN_S $root/compiler/[a-h]*.m .
+	$LN_S $root/compiler/[i-o]*.m .
+	$LN_S $root/compiler/[p-s]*.m .
+	$LN_S $root/compiler/[t-z]*.m .
+	$LN_S $root/compiler/*.pp .	
 
 	cp $root/compiler/Mmake* .
 	cd $root/stage2
 	mkdir library
 	cd library
-	ln -s $root/library/library.nu.nl.in .
-	ln -s $root/library/[a-l]*.m .
-	ln -s $root/library/[m-z]*.m .
-	ln -s $root/library/*.nl .
+	$LN_S $root/library/library.nu.nl.in .
+	$LN_S $root/library/[a-l]*.m .
+	$LN_S $root/library/[m-z]*.m .
+	$LN_S $root/library/*.nl .
 	cp $root/library/Mmake* .
-	ln -s $root/library/$STD_LIB_NAME.init .
+	$LN_S $root/library/$STD_LIB_NAME.init .
 	cd $root/stage2
 	mkdir browser
 	cd browser
-	ln -s $root/browser/*.m .
+	$LN_S $root/browser/*.m .
 	cp $root/browser/Mmake* .
-	ln -s $root/browser/$BROWSER_LIB_NAME.init .
+	$LN_S $root/browser/$BROWSER_LIB_NAME.init .
 	cd $root/stage2
 	if $copy_runtime
 	then
 		# Remove symbolic link to the stage 1 runtime if it's present,
 		# which it can be with the -2 option.
-		rm runtime
+		rm -f runtime
 		mkdir runtime
 		cd runtime
-		ln -s $root/runtime/*.h .
-		ln -s $root/runtime/*.c .
-		ln -s $root/runtime/*.in .
+		$LN_S $root/runtime/*.h .
+		$LN_S $root/runtime/*.c .
+		$LN_S $root/runtime/*.in .
 		cp $root/runtime/Mmake* .
-		ln -s $root/runtime/machdeps .
+		$LN_S $root/runtime/machdeps .
 		cd $root/stage2
-		rm trace
+		rm -f trace
 		mkdir trace
 		cd trace
-		ln -s $root/trace/*.h .
-		ln -s $root/trace/*.c .
+		$LN_S $root/trace/*.h .
+		$LN_S $root/trace/*.c .
 		cp $root/trace/Mmake* .
 		cd $root/stage2
 	else
-		ln -s $root/runtime .
-		ln -s $root/trace .
+		$LN_S $root/runtime .
+		$LN_S $root/trace .
 	fi
 	if $copy_boehm_gc
 	then
 		# Remove symbolic link to the stage 1 gc if it's present,
 		# which it can be with the -2 option.
-		rm boehm_gc
+		rm -f boehm_gc
 		mkdir boehm_gc
 		cd boehm_gc
-		ln -s $root/boehm_gc/*.h .
-		ln -s $root/boehm_gc/*.c .
-		ln -s $root/boehm_gc/*.s .
-		ln -s $root/boehm_gc/include .
+		$LN_S $root/boehm_gc/*.h .
+		$LN_S $root/boehm_gc/*.c .
+		$LN_S $root/boehm_gc/*.s .
+		$LN_S $root/boehm_gc/include .
 		cp $root/boehm_gc/Mmake* .
 		cp $root/boehm_gc/Makefile .
-		ln -s $root/boehm_gc/machdeps .
+		$LN_S $root/boehm_gc/machdeps .
 		cd $root/stage2
 	else
-		ln -s $root/boehm_gc .
+		$LN_S $root/boehm_gc .
 	fi
-	ln -s $root/doc .
-	ln -s $root/scripts .
-	ln -s $root/util .
+	$LN_S $root/doc .
+	$LN_S $root/scripts .
+	$LN_S $root/util .
 	if $copy_profiler
 	then
 		mkdir profiler
 		cd profiler
-		ln -s $root/profiler/*.m .
+		$LN_S $root/profiler/*.m .
 		cp $root/profiler/Mmake* .
 		cd $root/stage2
 	else
-		ln -s $root/profiler .
+		$LN_S $root/profiler .
 	fi
-	ln -s $root/conf* .
-	ln -s $root/aclocal.m4 .
-	ln -s $root/VERSION .
-	ln -s $root/.*.in .
+	$LN_S $root/conf* .
+	$LN_S $root/aclocal.m4 .
+	$LN_S $root/VERSION .
+	$LN_S $root/.*.in .
 	rm -f config*.log
 	cp $root/Mmake* .
 	if test -f $root/Mmake.stage.params
@@ -466,8 +476,8 @@ then
 	then
 		true
 	else
-		/bin/rm -f $root/stage2/library/[a-l]*.o < /dev/null
-		/bin/rm -f $root/stage2/library/[m-z]*.o < /dev/null
+		find $root/stage2/library -name "*.o" -print |
+		xargs /bin/rm -f
 	fi
 
 	MERCURY_COMPILER=$root/stage2/compiler/mercury_compile
@@ -498,40 +508,40 @@ then
 	# Break up the links into several chunks.
 	# This is needed to cope with small limits
 	# on the size of argument vectors.
-	ln -s $root/compiler/[a-h]*.m .
-	ln -s $root/compiler/[i-o]*.m .
-	ln -s $root/compiler/[p-s]*.m .
-	ln -s $root/compiler/[t-z]*.m .
-	ln -s $root/compiler/*.pp .	
+	$LN_S $root/compiler/[a-h]*.m .
+	$LN_S $root/compiler/[i-o]*.m .
+	$LN_S $root/compiler/[p-s]*.m .
+	$LN_S $root/compiler/[t-z]*.m .
+	$LN_S $root/compiler/*.pp .	
 
 	cp $root/compiler/Mmake* .
 	cd $root/stage3
 	mkdir library
 	cd library
-	ln -s $root/library/library.nu.nl.in .
-	ln -s $root/library/[a-l]*.m .
-	ln -s $root/library/[m-z]*.m .
-	ln -s $root/library/*.nl .
+	$LN_S $root/library/library.nu.nl.in .
+	$LN_S $root/library/[a-l]*.m .
+	$LN_S $root/library/[m-z]*.m .
+	$LN_S $root/library/*.nl .
 	cp $root/library/Mmake* .
-	ln -s $root/library/$STD_LIB_NAME.init .
+	$LN_S $root/library/$STD_LIB_NAME.init .
 	cd $root/stage3
 	mkdir browser
 	cd browser
-	ln -s $root/browser/*.m .
+	$LN_S $root/browser/*.m .
 	cp $root/browser/Mmake* .
-	ln -s $root/browser/$BROWSER_LIB_NAME.init .
+	$LN_S $root/browser/$BROWSER_LIB_NAME.init .
 	cd $root/stage3
-	ln -s $root/boehm_gc .
-	ln -s $root/doc .
-	ln -s $root/runtime .
-	ln -s $root/trace .
-	ln -s $root/scripts .
-	ln -s $root/util .
-	ln -s $root/profiler .
-	ln -s $root/conf* .
-	ln -s $root/aclocal.m4 .
-	ln -s $root/VERSION .
-	ln -s $root/.*.in .
+	$LN_S $root/boehm_gc .
+	$LN_S $root/doc .
+	$LN_S $root/runtime .
+	$LN_S $root/trace .
+	$LN_S $root/scripts .
+	$LN_S $root/util .
+	$LN_S $root/profiler .
+	$LN_S $root/conf* .
+	$LN_S $root/aclocal.m4 .
+	$LN_S $root/VERSION .
+	$LN_S $root/.*.in .
 	rm -f config*.log
 	cp $root/stage2/Mmake* .
 	cd $root
@@ -560,8 +570,18 @@ then
 	then
 		echo "building of stage 3 library successful"
 	else
-		echo "building of stage 3 library not successful"
-		exit 1
+		echo "building of stage 3 library initially not successful"
+		df .
+		# try again, in case the failure cause was transient
+		if 	(cd stage3/library &&
+			$MMAKE $mmake_opts $jfactor all-ints &&
+			$MMAKE $mmake_opts $jfactor cs)
+		then
+			echo "building of stage 3 library successful"
+		else
+			echo "building of stage 3 library not successful"
+			exit 1
+		fi
 	fi
 
 	# We delay deleting the stage 2 compiler objects until now,
@@ -574,25 +594,40 @@ then
 	then
 		true
 	else
-		/bin/rm -f $root/stage2/compiler/[a-l]*.o < /dev/null
-		/bin/rm -f $root/stage2/compiler/[i-s]*.o < /dev/null
-		/bin/rm -f $root/stage2/compiler/[t-z]*.o < /dev/null
+		find $root/stage2/compiler -name "*.o" -print |
+		xargs /bin/rm -f
 	fi
 
 	if (cd stage3/browser && $MMAKE $mmake_opts $jfactor cs)
 	then
 		echo "building of stage 3 browser successful"
 	else
-		echo "building of stage 3 browser not successful"
-		exit 1
+		echo "building of stage 3 browser initially not successful"
+		df .
+		# try again, in case the failure cause was transient
+		if (cd stage3/browser && $MMAKE $mmake_opts $jfactor cs)
+		then
+			echo "building of stage 3 browser successful"
+		else
+			echo "building of stage 3 browser not successful"
+			exit 1
+		fi
 	fi
 
 	if (cd stage3/compiler && $MMAKE $mmake_opts $jfactor cs)
 	then
 		echo "building of stage 3 compiler successful"
 	else
-		echo "building of stage 3 compiler not successful"
-		exit 1
+		echo "building of stage 3 compiler initially not successful"
+		df .
+		# try again, in case the failure cause was transient
+		if (cd stage3/compiler && $MMAKE $mmake_opts $jfactor cs)
+		then
+			echo "building of stage 3 compiler successful"
+		else
+			echo "building of stage 3 compiler not successful"
+			exit 1
+		fi
 	fi
 
 	diff_status=0
