Workaround the failure of some of the test cases in the term directory
Estimated hours taken: 1
Branches: main

Workaround the failure of some of the test cases in the term directory
in the .debug and .decldebug grades.  The test cases were not failing
as such, it was just that the argument size information produced by the
termination2 analysis in the debug grades looks a little different.

tests/term/Mmakefile:
	Allow the test cases in the term directory to have multiple
	expected outputs by allowing for .trans_opt_exp2 files.

tests/term/select.trans_opt_exp2:
tests/term/occur.trans_opt_exp2:
tests/term/pl4_01.trans_opt_exp2:
	The argument size information produced by the termination2
	analysis for these test cases in debug grades contains redundant
	constraints.  The redundant constraints are slipping by some of
	redundancy checks because the order of the constraints differs
	in the debug grades (due to differences in the HLDS between grades).
	While removing these redundant constraints is certainly
	possible, doing so is a relatively low priority task.

diff --git a/tests/term/Mmakefile b/tests/term/Mmakefile
--- a/tests/term/Mmakefile
+++ b/tests/term/Mmakefile
@@ -109,8 +109,24 @@ MCTRANSOPTFLAGS = $(MCTERMFLAGS) $(MCOPTFLAGS)
 ALL_MCTOIFLAGS+=$(MCTRANSOPTFLAGS)
 
 %.trans_opt_res: %.trans_opt_exp $(trans_opts_subdir)%.trans_opt
-	diff $(DIFF_OPTS) $*.trans_opt_exp $(trans_opts_subdir)$*.trans_opt \
-		> $@
+	@echo "Comparing $(trans_opts_subdir)$*.trans_opt with $*.trans_opt_exp2,"
+	@echo " results in $@"
+	@-rm -f $@ $*.trans_opt_res[1-2]
+	@{ diff $(DIFF_OPTS) $*.trans_opt_exp $(trans_opts_subdir)$*.trans_opt \
+			> $*.trans_opt_res1 && \
+		echo "Matches $*.trans_opt_exp" && \
+		cp $*.trans_opt_res1 $@; } || \
+	{ diff $(DIFF_OPTS) $*.trans_opt_exp2 $(trans_opts_subdir)$*.trans_opt \
+			> $*.trans_opt_res2 && \
+		echo "Matches $*.trans_opt_exp2" && \
+		cp $*.trans_opt_res2 $@; } || \
+	{ shortest=`wc -l $*.trans_opt_res[1-2] | grep -v total | sort -n | \
+		head -1 | awk '{ print $$2; }' `; \
+		echo "** $*.err did not match the expected error output"; \
+		echo "** (closest match was $$shortest)"; \
+		cp $$shortest $@; \
+		cat $@; \
+		exit 1; }
 
 #-----------------------------------------------------------------------------#
 
@@ -120,4 +136,3 @@ clean_local:
 realclean_local:
 	rm -f *.trans_opt_res
 
-#-----------------------------------------------------------------------------#
