Add support for thread-local backjumping in grades that support concurrency.
Estimated hours taken: 7
Branches: main

Add support for thread-local backjumping in grades that support concurrency.

library/backjump.m:
	Shift the C definition of backjump handlers and choice ids into the
	runtime.  This is needed because MR_Context now refers to them and
	the runtime should not depend on the library.

	Delete the XXX comment regarding pred_is_external/3.  (This has been
	fixed below.)

runtime/mercury_backjump.h:
runtime/mercury_backjump.c:
	New module that defines those parts of the backjumping support that
	the runtime requires access to.

	In high-level C .par grades make the global state required by
	backjumping thread-specific.

	Conform to the usual coding conventions in the runtime in the new
	versions of the data structures that were originally in backjump.m.

	Rename ML_Choice_Id to MR_BackJumpChoiceId, the latter is less
	ambiguous.

runtime/mercury_context.h:
runtime/mercury_context.c:
	In low-level C grades add two extra fields to the MR_Context structure
	to hold the global state required by backjumping.

	In high-level C .par grades initialise the the thread-specific data that
	is used to store the backjump global state at program startup.

	Reformat a function prototype.

runtime/mercury_thread.h:
	Reformat a function prototype.

runtime/Mmakefile:
	Include the new files.

mdbcomp/program_representation.m:
	Update pred_is_external/3 to include backjump.builtin_choice_id/1
	and backjump.builtin_backjump/1.

tests/hard_coded/Mmakefile:
tests/hard_coded/tl_backjump_test.m:
tests/hard_coded/tl_backjump_test.exp:
	Test thread-local backjumping.

tests/hard_coded/tl_backjump_test.exp2:
	Expected output for the above test case for grades in which spawn/3
	does not work.

diff --git a/tests/hard_coded/Mmakefile b/tests/hard_coded/Mmakefile
--- a/tests/hard_coded/Mmakefile
+++ b/tests/hard_coded/Mmakefile
@@ -473,6 +473,8 @@ endif
 # defined.
 #
 # backjump_test fails because deep profiler cannot yet handle backjumps.
+# tl_backjump_test fails because the deep profiler cannot yet handle
+# backjumps and threads.
 
 ifeq "$(findstring profdeep,$(GRADE))" ""
 	NON_PROFDEEP_PROGS = \
@@ -491,6 +493,7 @@ ifeq "$(findstring profdeep,$(GRADE))" ""
 		solver_default_eq_cmp \
 		test_array2d \
 		test_injection \
+		tl_backjump_test \
 		user_defined_equality \
 		version_array_test \
 		write_binary
@@ -670,7 +673,7 @@ no_fully_strict.out: no_fully_strict
 			< $@.tmp > $@; \
 		rm -f $@.tmp; \
 	fi
-
+		
 # final_excp.out is expected to fail (it calls throw/1).
 #
 final_excp.out: final_excp
@@ -742,6 +745,20 @@ runtime_opt.out: runtime_opt runtime_opt.inp
 			echo ""; \
 		done \
 	) > runtime_opt.out 2>&1
+
+# The test checks the output from multiple threads and since that output
+# may be interleaved arbitrarily we need to filter it so that all the output
+# from each thread appears sequentially in a block.
+tl_backjump_test.out: tl_backjump_test
+	if ./tl_backjump_test > $@.tmp 2>&1; then \
+		grep "^(TID: #2" $@.tmp > $@; \
+		grep "^(TID: #3" $@.tmp >> $@; \
+		grep "^spawn"    $@.tmp >> $@; \
+		rm -f $@.tmp; \
+	else \
+		grep . $@.tmp; \
+		exit 1; \
+	fi	
 
 #-----------------------------------------------------------------------------#
 
