Add Unix-style man pages for most of the Mercury development tools.
scripts/c2init.in:
scripts/mmake.in:
scripts/msc.in:
	Small changes to the help messages to make them come out
	better when converted to man pages.

scripts/mgnuc.in:
	Add a `--help' option.

diff --git a/scripts/c2init.in b/scripts/c2init.in
--- a/scripts/c2init.in
+++ b/scripts/c2init.in
@@ -11,23 +11,28 @@
 # This script outputs an appropriate init.c, given the .c files.
 # Type `c2init --help' for usage message.
 #
-# Environment variables: MERCURY_MOD_LIB_DIR, MERCURY_MOD_LIB_MODS,
-# MERCURY_MKINIT.
 
-Usage="\
-Usage: c2init [options] modules ...
+# IMPORTANT: the manpage is produced automatically from this help
+# message, so if you change the help message, don't forget to check
+# that the manpage still looks OK.
+Help="\
+Name:	c2init - Create Mercury initialization file.
+Usage:	c2init [options] modules ...
 Options: 
--l, --library
-	Don't generate a \`main()' function.
-	Instead, generate a function
-		mercury_main(int argc, char **argv, char *stack_bottom);
-	(declared in \"init.h\") that can be called from C code.
--c <n>, --max-calls <n>
-	Break up the initialization into groups of at most <n> function calls.
-	(Default value of <n> is 40.)
--w <label>, --entry-point <label>
-	Set entry point to <label>.
-	(Default value is \`mercury__io__run_0_0'.)"
+	-l, --library
+		Don't generate a \`main()' function.
+		Instead, generate a function
+			mercury_main(int argc, char **argv, char *stack_bottom);
+		(declared in \"init.h\") that can be called from C code.
+	-c <n>, --max-calls <n>
+		Break up the initialization into groups of at most <n> function
+		calls.  (Default value of <n> is 40.)
+	-w <label>, --entry-point <label>
+		Set entry point to <label>.
+		(Default value is \`mercury__io__run_0_0'.)
+Environment variables:
+	MERCURY_MOD_LIB_DIR, MERCURY_MOD_LIB_MODS, MERCURY_MKINIT.
+"
 
 MERCURY_MOD_LIB_DIR=${MERCURY_MOD_LIB_DIR=@LIBDIR@/modules}
 MERCURY_MOD_LIB_MODS=${MERCURY_MOD_LIB_MODS=$MERCURY_MOD_LIB_DIR/*}
@@ -48,12 +53,13 @@ while true; do
 	-l-|--no-library)
 		library_opt=""; shift;;
 	-h|--help|"-?")
-		echo "$Usage"
+		echo "$Help"
 		exit 0;;
 	--)
 		shift; break;;
 	-*)
-		echo "$Usage" 1>&2;
+		echo "`basename $0`: invalid option \`$1'" 1>&2;
+		echo "Try \`$0 --help' for help." 1>&2;
 		exit 1;;
 	*)
 		break;;
