Remove some old special-case stuff (if $host = kryten ...).
scripts/ml.in:
	Remove some old special-case stuff (if $host = kryten ...).

	Change it so that it uses $CC as determined by configure
	rather than hard-coding gcc.

	Use a named pipe to invoke the demangler, so that we
	return the exit status of the C compiler, not the demangler.

	Add a new option --no-libs which suppresses the linking
	in of the libraries; this is useful if you want to link
	a shared library and have the output of the linker passed
	through the demangler.

scripts/mmake.in:
	Use a new environment variable MMAKE_DIR as the location to
	look for both Mmake.vars and Mmake.rules; this is simpler than
	use the MMAKE_VARS and MMAKE_RULES environment variables.

diff --git a/scripts/ml.in b/scripts/ml.in
--- a/scripts/ml.in
+++ b/scripts/ml.in
@@ -16,7 +16,7 @@
 #		Echo gcc command line before executing it
 #	-s <grade>, --grade <grade>
 #		Specify which grade of the Mercury library to link with.
-#		Defaults to `asm_fast.gc'.
+#		(The default grade is determined by `configure'.)
 #
 # Environment variables: MERCURY_C_LIB_DIR, MERCURY_DEFAULT_GRADE
 
@@ -24,6 +24,7 @@ LIBDIR=${MERCURY_C_LIB_DIR=@LIBDIR@/lib}
 DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
 # DEMANGLER=${MERCURY_DEMANGLER=@LIBDIR@/bin/@FULLARCH@/mdemangle}
 DEMANGLER=${MERCURY_DEMANGLER=mdemangle}
+CC=${MERCURY_C_COMPILER=@CC@}
 
 verbose=false
 GRADE=$DEFAULT_GRADE
@@ -37,10 +38,13 @@ while true; do
 		shift
 		GRADE="$1"
 		shift ;;
+	--no-libs)
+		MERCURY_LIBS=
+		shift ;;
 	--)
 		shift
 		break ;;
-	-static)
+	-static|-shared)
 		break ;;
 	-s*)
 		GRADE="` expr $1 : '-s\(.*\)' `"
@@ -58,6 +62,8 @@ case "$GRADE" in
 		LIBGC=
 		;;
 esac
+
+LIBS=${MERCURY_LIBS="-lmer -lmercury -lmer $LIBGC"}
 
 case @FULLARCH@ in
 	*-solaris*)
@@ -93,18 +99,27 @@ LIBRARY_PATH="/usr/contrib/lib/nonshared:/usr/lib/nonshared:$LIBRARY_PATH"
 		;;
 esac
 
-case "`hostname`" in
-	cadillac.dd.citri.edu.au)
-		GCC=/usr/local/bin/gcc ;;
-	kryten.cs.mu.OZ.AU)
-		GCC=/usr/local/bin/gcc ;;
-	*)
-		GCC=${GCC=gcc}
-esac
-
 if $verbose; then
-	echo $GCC $ARCH_OPTS "$@" $LIBDIR_OPTS -lmer -lmercury -lmer $LIBGC \
-		"2>&1 | $DEMANGLER 1>&2"
+	echo $CC $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS "|"
+	echo "$DEMANGLER"
 fi
-exec $GCC $ARCH_OPTS "$@" $LIBDIR_OPTS -lmer -lmercury -lmer $LIBGC 2>&1 |
-exec $DEMANGLER 1>&2
+
+# we would like to just run $CC and pipe the result into $DEMANGLER,
+# but `$CC | $DEMANGLER' would return the wrong exit status, so
+# we need to use a named pipe
+
+	# create the pipe, making sure we remove it if interrupted
+PIPE=/tmp/ml.$$
+trap 'rm -f $PIPE' 0 1 2 3 13 15 
+mkfifo $PIPE
+	# execute the demangler in the background,
+	# with stdin coming from the pipe and with stdout redirected to stderr
+exec $DEMANGLER 1>&2 < $PIPE &
+	# redirect our stdout and stderr into the pipe
+exec >$PIPE 2>&1
+	# now we can remove the pipe; since is an open file, it will stay
+	# around until $CC and $DEMANGLER exit
+rm -f $PIPE
+	# finally execute $CC;
+	# stdout & stderr will go via the pipe to $DEMANGLER and then to stderr
+exec $CC $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS
