Improve the error messages for linking objects compiled in different grades.
Estimated hours taken: 1

Improve the error messages for linking objects compiled in different grades.

util/mdemangle.c:
	Check for `MR_grade_*' and `MR_runtime_grade', and if they are
	found, print out a message explaining the cause of the problem.
	But only do that if a new option `--explain-link-errors' is set,
	so that this message will only come out when you get a message
	from the linker, not when you invoke mdemangle manually e.g.
	via `nm *.o | mdemangle'.

scripts/ml.in:
	Pass the new `--explain-link-errors' option to mdemangle.

diff --git a/scripts/ml.in b/scripts/ml.in
--- a/scripts/ml.in
+++ b/scripts/ml.in
@@ -575,7 +575,7 @@ case $verbose in
 	    true)
 		echo $LINKER $UNDEF_OPT $STRIP_OPTS $MAYBE_STATIC_OPT \
 			$ARCH_OPTS $LIBDIR_OPTS $RPATH_OPT_LIST "$@" $LIBS "|"
-		echo "$DEMANGLER"
+		echo "$DEMANGLER --explain-link-errors"
 		;;
 	esac
 	;;
@@ -605,7 +605,7 @@ case $demangle in
 	$MKFIFO $PIPE
 		# execute the demangler in the background, with stdin 
 		# coming from the pipe and with stdout redirected to stderr
-	exec $DEMANGLER 1>&2 < $PIPE &
+	exec $DEMANGLER --explain-link-errors 1>&2 < $PIPE &
 		# redirect our stdout and stderr into the pipe
 	exec >$PIPE 2>&1
 		# now we can remove the pipe; since is an open file, it will
