Fix two security holes in the way temporary files in /tmp are handled.
Estimated hours taken: 1

Fix two security holes in the way temporary files in /tmp are handled.

configure.in:
	Look for mktemp.

scripts/ml.in:
	Previously, if a file /tmp/ml$$ existed, linker errors would
	be missed (or fake linker errors could be provided).
	Use
		mkdir /tmp/ml.$$ || exit 1
	approach to create a directory, then use a file in that
	directory as the fifo for linker errors.

scripts/mmake.in:
	Previously, if a file /tmp/mmake.$$ existed, it would stop
	the generation of a mmake file, and the system would invoke
	gmake on the existing file (possibly executing arbitrary
	commands).
	Use mktemp (if available) to create the file, and exit if
	it is not possible to create the file.
	If mktemp is not available, use mkdir || exit 1 technique.

diff --git a/scripts/ml.in b/scripts/ml.in
--- a/scripts/ml.in
+++ b/scripts/ml.in
@@ -417,8 +417,16 @@ case $demangle in
 	# pipes, then we don't use the demangler
 
 		# create the pipe, making sure we remove it if interrupted
-	PIPE=/tmp/ml.$$
-	trap 'rm -f $PIPE; exit 1' 1 2 3 13 15 
+	old_umask=`umask`
+	umask 022
+	ML_TMPDIR=/tmp/ml$$
+	PIPE=$ML_TMPDIR/pipe
+	if ! mkdir $ML_TMPDIR ; then
+		echo "Unable to create temporary pipe" 1>&2
+		exit 1
+	fi
+	trap 'rm -rf $ML_TMPDIR; exit 1' 1 2 3 13 15 
+	umask $old_umask
 	$MKFIFO $PIPE
 		# execute the demangler in the background, with stdin 
 		# coming from the pipe and with stdout redirected to stderr
@@ -427,7 +435,7 @@ case $demangle in
 	exec >$PIPE 2>&1
 		# now we can remove the pipe; since is an open file, it will
 		# stay around until $CC and $DEMANGLER exit
-	rm -f $PIPE
+	rm -rf $ML_TMPDIR
 		# finally execute $CC; stdout & stderr will
 		# go via the pipe to $DEMANGLER and then to stderr
 	;;
diff --git a/scripts/mmake.in b/scripts/mmake.in
--- a/scripts/mmake.in
+++ b/scripts/mmake.in
@@ -59,6 +59,7 @@ MMAKE_VARS=${MMAKE_VARS=$MMAKE_DIR/Mmake.vars}
 MMAKE_RULES=${MMAKE_RULES=$MMAKE_DIR/Mmake.rules}
 MERCURY_INT_DIR=${MERCURY_INT_DIR=@LIBDIR@/ints}
 MERCURY_DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
+MKTEMP=@MKTEMP@
 
 MMAKE=$0
 verbose=false
@@ -148,8 +149,24 @@ MMAKE_USE_SUBDIRS=$use_subdirs
 if $save_makefile; then
 	tmp=Mmake.makefile
 else
-	tmp=/tmp/mmake.$$
-	trap 'status=$?; rm -f $tmp; exit $status' 0 1 2 3 13 15
+	case "$MKTEMP" in
+		"") 	old_umask=`umask`
+			umask 022
+			mmake_tmpdir=/tmp/mmake$$
+			tmp=$mmake_tmpdir/mmake
+			if ! mkdir $mmake_tmpdir ; then
+				echo "Unable to create temporary makefile" 1>&2
+				exit 1
+			fi
+			trap 'status=$?; rm -rf $mmake_tmpdir; exit $status' 0 1 2 3 13 15
+			umask $old_umask
+			;;
+		*)
+			# mktemp should give its own error message.
+			tmp=`$MKTEMP /tmp/mmake.XXXXXX` || exit 1
+			trap 'status=$?; rm -f $tmp; exit $status' 0 1 2 3 13 15
+			;;
+	esac
 fi
 
 MMAKE_MAKE_CMD="${MMAKE_MAKE} -f $tmp -r"
@@ -176,7 +193,7 @@ if $verbose; then
 	echo export MERCURY_INT_DIR
 	echo MERCURY_DEFAULT_GRADE=$MERCURY_DEFAULT_GRADE
 	echo export MERCURY_DEFAULT_GRADE
-	echo cat ${MMAKE_VARS} $deps $ds $mmake ${MMAKE_RULES} ">" $tmp
+	echo cat ${MMAKE_VARS} $deps $ds $mmake ${MMAKE_RULES} ">>" $tmp
 	echo ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} -f $tmp -r "$@"
 fi
 export MMAKE
