In `ml', use the value of $MKFIFO determined by configure; if configure can't find `mkfifo', configure will look for `mknod', and set MKFIFO to `mkfifo_using_mknod', which is a new script that basically just invokes `mknod $1 p'.  Also, add a new option --no-demangle; if this option is used, or if the system doesn't have either `mknod' or `mkfifo', then demangling is disabled.
These changes are all because some systems (e.g. SunOS 4.1.3)
don't have `mkfifo'.

diff --git a/scripts/ml.in b/scripts/ml.in
--- a/scripts/ml.in
+++ b/scripts/ml.in
@@ -14,6 +14,8 @@
 # Options:
 # 	-v, --verbose
 #		Echo gcc command line before executing it
+# 	--no-demangle
+#		Don't pipe the output of the linker the Mercury demangler
 # 	-g, --no-strip
 #		Do not strip debugging information
 #	-s <grade>, --grade <grade>
@@ -28,15 +30,23 @@ DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE=@DEFAULT_GRADE@}
 # DEMANGLER=${MERCURY_DEMANGLER=@LIBDIR@/bin/@FULLARCH@/mdemangle}
 DEMANGLER=${MERCURY_DEMANGLER=mdemangle}
 CC=${MERCURY_C_COMPILER=@CC@}
+MKFIFO=${MERCURY_MKFIFO=@MKFIFO@}
 
 verbose=false
 strip=true
+demangle=true
 GRADE=$DEFAULT_GRADE
 
 while true; do
     case "$1" in
 	-v|--verbose)
 		verbose=true
+		shift ;;
+	--demangle)
+		demangle=true
+		shift ;;
+	--no-demangle)
+		demangle=false
 		shift ;;
 	-s|--grade)
 		shift
@@ -117,31 +127,47 @@ LIBRARY_PATH="$NONSHARED_LIB_DIR:/usr/lib/nonshared:$LIBRARY_PATH"
 		;;
 esac
 
-case $verbose in
-	true)	echo $CC $STRIP_OPTS $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS "|"
-		echo "$DEMANGLER"
-		;;
-	false)	;;
+case "$MKFIFO" in
+    none) demangle=false ;;
 esac
 
-# we would like to just run $CC and pipe the result into $DEMANGLER,
-# but `$CC | $DEMANGLER' would return the wrong exit status, so
-# we need to use a named pipe
+case $verbose in
+    true)
+	case $demangle in
+	    false)
+		echo $CC $STRIP_OPTS $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS
+		;;
+	    true)
+		echo $CC $STRIP_OPTS $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS "|"
+		echo "$DEMANGLER"
+		;;
+	esac
+	;;
+esac
 
-	# create the pipe, making sure we remove it if interrupted
-PIPE=/tmp/ml.$$
-trap 'rm -f $PIPE' 0 1 2 3 13 15 
-mkfifo $PIPE
-	# execute the demangler in the background,
-	# with stdin coming from the pipe and with stdout redirected to stderr
-exec $DEMANGLER 1>&2 < $PIPE &
-	# redirect our stdout and stderr into the pipe
-exec >$PIPE 2>&1
-	# now we can remove the pipe; since is an open file, it will stay
-	# around until $CC and $DEMANGLER exit
-rm -f $PIPE
-	# finally execute $CC;
-	# stdout & stderr will go via the pipe to $DEMANGLER and then to stderr
+case $demangle in
+    true)
+	# we would like to just run $CC and pipe the result into $DEMANGLER,
+	# but `$CC | $DEMANGLER' would return the wrong exit status, so
+	# we need to use a named pipe; if the system doesn't have named
+	# pipes, then we don't use the demangler
+
+		# create the pipe, making sure we remove it if interrupted
+	PIPE=/tmp/ml.$$
+	trap 'rm -f $PIPE; exit 1' 1 2 3 13 15 
+	$MKFIFO $PIPE
+		# execute the demangler in the background, with stdin 
+		# coming from the pipe and with stdout redirected to stderr
+	exec $DEMANGLER 1>&2 < $PIPE &
+		# redirect our stdout and stderr into the pipe
+	exec >$PIPE 2>&1
+		# now we can remove the pipe; since is an open file, it will
+		# stay around until $CC and $DEMANGLER exit
+	rm -f $PIPE
+		# finally execute $CC; stdout & stderr will
+		# go via the pipe to $DEMANGLER and then to stderr
+	;;
+esac
 case $# in
 	0) exec $CC $STRIP_OPTS $ARCH_OPTS $LIBDIR_OPTS $LIBS ;;
 	*) exec $CC $STRIP_OPTS $ARCH_OPTS "$@" $LIBDIR_OPTS $LIBS ;;
