Update the programming style of more scripts.
scripts/c2init.in:
scripts/mercury.in:
scripts/mmake.in:
scripts/mmc.in:
scripts/prepare_install_dir.in:
    Indent by four spaces, not by tabs, or by three spaces.

    Use ${varname}, not just $varname.

    Put successive commands on separate lines.

    Indent case statements in a consistent manner: put case patterns
    on their own lines; put ;;s on their own lines.

    Put quotes around strings that should be considered one word
    even if they are empty or contain spaces.

diff --git a/scripts/mmake.in b/scripts/mmake.in
--- a/scripts/mmake.in
+++ b/scripts/mmake.in
@@ -33,7 +33,7 @@ Options:
         subdirectory, then this option is the default.)
     --target c:
         Compile to C. This is the default."
-Help="$Help
+Help="${Help}
     --mercury-standard-library-directory <directory>
     --mercury-stdlib-dir <directory>:
         The directory containing the installed Mercury standard
@@ -80,7 +80,7 @@ TMPDIR=${TMPDIR=/tmp}
 # Set the MACOSX_DEPLOYMENT_TARGET environment variable if needed.
 @SET_MACOSX_DEPLOYMENT_TARGET@
 
-MMAKE=$0
+MMAKE="$0"
 include_makefile=
 verbose=false
 save_makefile=false
@@ -93,11 +93,11 @@ fi
 use_mmc_make=${MMAKE_USE_MMC_MAKE=no}
 warn_undefined_vars=true
 
-while test $# -gt 0
+while test "$#" -gt 0
 do
     case "$1" in
         -h|--help)
-            echo "$Help"
+            echo "${Help}"
             exit 0
             ;;
         --use-subdirs)
@@ -128,12 +128,12 @@ do
             ;;
         -s|--save-makefile)
             save_makefile=true
-            MMAKE="$MMAKE $1"
+            MMAKE="${MMAKE} $1"
             shift
             ;;
         -s-|--no-save-makefile)
             save_makefile=false
-            MMAKE="$MMAKE $1"
+            MMAKE="${MMAKE} $1"
             shift
             ;;
         -f|--file)
@@ -143,12 +143,12 @@ do
             ;;
         -v|--verbose)
             verbose=true
-            MMAKE="$MMAKE $1"
+            MMAKE="${MMAKE} $1"
             shift
             ;;
         -v-|--no-verbose)
             verbose=false
-            MMAKE="$MMAKE $1"
+            MMAKE="${MMAKE} $1"
             shift
             ;;
         -w|--warn-undefined-vars)
@@ -161,8 +161,8 @@ do
             ;;
         --include-makefile)
             # XXX check that $2 exists first
-            MMAKE="$MMAKE $1 $2"
-            include_makefile="$include_makefile $2"
+            MMAKE="${MMAKE} $1 $2"
+            include_makefile="${include_makefile} $2"
             shift
             shift
             ;;
@@ -185,7 +185,7 @@ do
         # without `MERCURY_STDLIB_DIR' also being unset.
 
         --)
-            MMAKE="$MMAKE $1"
+            MMAKE="${MMAKE} $1"
             shift
             break
             ;;
@@ -197,33 +197,33 @@ done
 
 # With `mmc --make' we need to use subdirs to avoid make trying to
 # use Mmake rules to build the `.o' files for Mercury modules.
-case $use_mmc_make in
+case "${use_mmc_make}" in
     yes)
         use_subdirs=yes
         ;;
 esac
 
-if test "$MERCURY_CONFIG_DIR" != ""
+if test "${MERCURY_CONFIG_DIR}" != ""
 then
-    MMAKE_DIR=${MMAKE_DIR=$MERCURY_CONFIG_DIR/mmake}
+    MMAKE_DIR=${MMAKE_DIR=${MERCURY_CONFIG_DIR}/mmake}
     export MERCURY_CONFIG_DIR
     export MERCURY_STDLIB_DIR
 fi
 
-case "$MMAKE_DIR" in
+case "${MMAKE_DIR}" in
     "")
         echo "mmake: MMAKE_DIR not set"
         exit 1
         ;;
     *)
-        MMAKE_VARS=${MMAKE_VARS=$MMAKE_DIR/Mmake.vars}
-        MMAKE_RULES=${MMAKE_RULES=$MMAKE_DIR/Mmake.rules}
+        MMAKE_VARS=${MMAKE_VARS=${MMAKE_DIR}/Mmake.vars}
+        MMAKE_RULES=${MMAKE_RULES=${MMAKE_DIR}/Mmake.rules}
         ;;
 esac
 
-if test "$mmake" = ""
+if test "${mmake}" = ""
 then
-    if test "$MMAKEFILE" = ""
+    if test "${MMAKEFILE}" = ""
     then
         if test -f Mmakefile
         then
@@ -238,86 +238,88 @@ then
         fi
     fi
 else
-    MMAKEFILE="$mmake"
+    MMAKEFILE="${mmake}"
 fi
 
-case $use_subdirs in
+case "${use_subdirs}" in
     no)
         dvs="`echo *.dv`"
-        if test "$dvs" = "*.dv"
+        if test "${dvs}" = "*.dv"
         then
             dvs=""
         fi
         deps="`echo *.dep`"
-        if test "$deps" = "*.dep"
+        if test "${deps}" = "*.dep"
         then
             deps=""
         fi
         ds="`echo *.d`"
-        if test "$ds" = "*.d"
+        if test "${ds}" = "*.d"
         then
             ds=""
         fi
         ;;
     yes)
         dvs="`echo Mercury/deps/*.dv`"
-        if test "$dvs" = "Mercury/deps/*.dv"
+        if test "${dvs}" = "Mercury/deps/*.dv"
         then
             dvs=""
         fi
         deps="`echo Mercury/deps/*.dep`"
-        if test "$deps" = "Mercury/deps/*.dep"
+        if test "${deps}" = "Mercury/deps/*.dep"
         then
             deps=""
         fi
         ds="`echo Mercury/ds/*.d`"
-        if test "$ds" = "Mercury/ds/*.d"
+        if test "${ds}" = "Mercury/ds/*.d"
         then
             ds=""
         fi
         ;;
 esac
 
-MMAKE_USE_SUBDIRS=$use_subdirs
-MMAKE_USE_MMC_MAKE=$use_mmc_make
+MMAKE_USE_SUBDIRS=${use_subdirs}
+MMAKE_USE_MMC_MAKE=${use_mmc_make}
 
-if $save_makefile
+if "${save_makefile}"
 then
     tmp=Mmake.makefile
 else
-    case "$MKTEMP" in
+    case "${MKTEMP}" in
         "")
             old_umask=`umask`
             umask 022
             try=0
             until
-                mmake_tmpdir=$TMPDIR/mmake$$-$try
-                tmp=$mmake_tmpdir/mmake
-                trap 'rmdir $mmake_tmpdir >/dev/null 2>&1; exit 1' \
+                mmake_tmpdir=${TMPDIR}/mmake$$-${try}
+                tmp=${mmake_tmpdir}/mmake
+                trap 'rmdir ${mmake_tmpdir} >/dev/null 2>&1; exit 1' \
                     1 2 3 13 15
-                mkdir $mmake_tmpdir
+                mkdir ${mmake_tmpdir}
             do
-                try=`expr $try + 1`
-                # give up after 20 tries
-                case $try in 20)
-                    echo "mmake: unable to create directory" \
-                        "for temporary makefile" 1>&2
-                    exit 1
+                try=`expr ${try} + 1`
+                # Give up after 20 tries.
+                case ${try} in
+                    20)
+                        echo "mmake: unable to create directory" \
+                            "for temporary makefile" 1>&2
+                        exit 1
+                        ;;
                 esac
             done
-            trap 'status=$?; rm -rf $mmake_tmpdir; exit $status' \
+            trap 'status=$?; rm -rf ${mmake_tmpdir}; exit ${status}' \
                 0 1 2 3 13 15
-            umask $old_umask
+            umask ${old_umask}
             ;;
         *)
             # mktemp should give its own error message.
-            tmp=`$MKTEMP $TMPDIR/mmake.XXXXXX` || exit 1
-            trap 'status=$?; rm -f $tmp; exit $status' 0 1 2 3 13 15
+            tmp=`${MKTEMP} ${TMPDIR}/mmake.XXXXXX` || exit 1
+            trap 'status=$?; rm -f ${tmp}; exit ${status}' 0 1 2 3 13 15
             ;;
     esac
 fi
 
-MMAKE_MAKE_CMD="${MMAKE_MAKE} -f $tmp -r"
+MMAKE_MAKE_CMD="${MMAKE_MAKE} -f ${tmp} -r"
 
 # Enable checking for undefined variables -- but not when making the
 # dependencies, or when cleaning up, because in either of those two cases
@@ -328,38 +330,42 @@ case "$@" in
         MMAKE_MAKE_OPTS=""
         ;;
     *)
-        case $warn_undefined_vars in
-            true)   MMAKE_MAKE_OPTS="--warn-undefined-variables" ;;
-            false)  MMAKE_MAKE_OPTS="" ;;
+        case "${warn_undefined_vars}" in
+            true)
+                MMAKE_MAKE_OPTS="--warn-undefined-variables"
+                ;;
+            false)
+                MMAKE_MAKE_OPTS=""
+                ;;
         esac
         ;;
 esac
 
 # For backwards compatibility/bootstrapping:
 # if no `.dv' files exist, use the `.dep' files instead.
-if test "$dvs" = ""
+if test "${dvs}" = ""
 then
-    dvs=$deps
+    dvs=${deps}
     deps=
 fi
 
-if $verbose
+if "${verbose}"
 then
-    echo MMAKE=$MMAKE
+    echo MMAKE=${MMAKE}
     echo export MMAKE
-    echo MMAKE_MAKE_CMD=$MMAKE_MAKE_CMD
+    echo MMAKE_MAKE_CMD=${MMAKE_MAKE_CMD}
     echo export MMAKE_MAKE_CMD
-    echo MMAKE_USE_SUBDIRS=$MMAKE_USE_SUBDIRS
+    echo MMAKE_USE_SUBDIRS=${MMAKE_USE_SUBDIRS}
     echo export MMAKE_USE_SUBDIRS
-    echo MMAKE_USE_MMC_MAKE=$MMAKE_USE_MMC_MAKE
+    echo MMAKE_USE_MMC_MAKE=${MMAKE_USE_MMC_MAKE}
     echo export MMAKE_USE_MMC_MAKE
-    echo MERCURY_DEFAULT_GRADE=$MERCURY_DEFAULT_GRADE
+    echo MERCURY_DEFAULT_GRADE=${MERCURY_DEFAULT_GRADE}
     echo export MERCURY_DEFAULT_GRADE
-    echo MMAKEFILE=$MMAKEFILE
+    echo MMAKEFILE=${MMAKEFILE}
     echo export MMAKEFILE
-    echo cat ${MMAKE_VARS} $include_makefile $MMAKEFILE $ds $dvs $deps \
-        ${MMAKE_RULES}">>" $tmp
-    echo ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} -f $tmp -r "$@"
+    echo cat ${MMAKE_VARS} ${include_makefile} ${MMAKEFILE} \
+        ${ds} ${dvs} ${deps} ${MMAKE_RULES}">>" ${tmp}
+    echo ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} -f ${tmp} -r "$@"
 fi
 export MMAKE
 export MMAKE_MAKE_CMD
@@ -367,7 +373,7 @@ export MMAKE_USE_SUBDIRS
 export MMAKE_USE_MMC_MAKE
 export MERCURY_DEFAULT_GRADE
 export MMAKEFILE
-# XXX The $dvs and $ds variables can be so long as to overflow size limits
+# XXX The ${dvs} and ${ds} variables can be so long as to overflow size limits
 # on command lines, so we use xargs. Echo doesn't quote the file names
 # correctly, but this is not a problem in practice because none of our
 # file names contain any special characters.
@@ -375,24 +381,28 @@ export MMAKEFILE
 # that has been carved out of modules.m over the years.
 {
 cat ${MMAKE_VARS}
-echo $dvs | xargs cat
-echo $include_makefile $MMAKEFILE | xargs cat
+echo ${dvs} | xargs cat
+echo ${include_makefile} ${MMAKEFILE} | xargs cat
 echo 'ifneq ($(MMAKE_AUTO_INCLUDE_DS),no)'
-echo $ds | xargs cat
+echo ${ds} | xargs cat
 echo 'endif'
-cat $deps ${MMAKE_RULES}
-} > $tmp
+cat ${deps} ${MMAKE_RULES}
+} > ${tmp}
 
-if test "$MMAKE_DEBUG" != ""
+if test "${MMAKE_DEBUG}" != ""
 then
     MMAKE_DEBUG_OPTS="-d"
 else
     MMAKE_DEBUG_OPTS=""
 fi
 
-case $# in
+case "$#" in
     # Note that we can't use `exec' here, because if we did that,
-    # that `trap' code which removes $tmp would never get executed.
-    0) ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} ${MMAKE_DEBUG_OPTS} -f $tmp -r ;;
-    *) ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} ${MMAKE_DEBUG_OPTS} -f $tmp -r "$@" ;;
+    # that `trap' code which removes ${tmp} would never get executed.
+    0)
+        ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} ${MMAKE_DEBUG_OPTS} -f ${tmp} -r
+        ;;
+    *)
+        ${MMAKE_MAKE} ${MMAKE_MAKE_OPTS} ${MMAKE_DEBUG_OPTS} -f ${tmp} -r "$@"
+        ;;
 esac
