Bring the style of some scripts up to date ...
... by replacing tabs with spaces, adding modelines, replacing [ with test,
and fixing indentation.

diff --git a/scripts/mmake.in b/scripts/mmake.in
--- a/scripts/mmake.in
+++ b/scripts/mmake.in
@@ -1,6 +1,8 @@
 #! /bin/sh
-# @configure_input@
+#---------------------------------------------------------------------------#
 # vim: ts=4 sw=4 et ft=sh
+#---------------------------------------------------------------------------#
+# @configure_input@
 #---------------------------------------------------------------------------#
 # Copyright (C) 1995-1999,2001-2005 The University of Melbourne.
 # Copyright (C) 2013, 2016, 2019, 2020 The Mercury team.
@@ -116,10 +118,11 @@ do
             ;;
         --target)
             case "$2" in
-                c)  ;;
-                *)  echo "$0: invalid argument to" \
-                        "\`--target' option" 1>&2
-                    exit 1 ;;
+                c)
+                    ;;
+                *)  echo "$0: invalid argument to" "\`--target' option" 1>&2
+                    exit 1
+                    ;;
             esac
             shift; shift
             ;;
