Link to absolute, not relative path names, since relative path names
Estimated hours taken: 2

bootcheck, binary, linear:
	Link to absolute, not relative path names, since relative path names
	do not work back across symbolic links.

binary, linear:
	Allow the user to give an initial list of suspects.

assemble, binary, linear:
	Allow negative searches, i.e. searches in which the base version is
	the bad version and we want to see which module "fixes" the problem
	caused by the other modules, as opposed to normal searches in which
	we are looking for the module that introduces the problem.

diff --git a/tools/binary b/tools/binary
--- a/tools/binary
+++ b/tools/binary
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script find miscompiled procedures.
+# This script finds miscompiled procedures.
 #
 # Given a stage2 directory that works (stage2.ok) and one that doesn't
 # (stage2.bad), this script uses binary search to try to find in stage2.bad
@@ -21,19 +21,31 @@ Options:
 		Do not perform a bootcheck; check only the tests directory.
 	-c, --compile-only
 		Compile only. Do not compare stage2.ok and stage3.
+	-d <dirname>, --dir <dirname>
+		Confine the search to one directory, library or compiler.
+		(Usually useful only after a previous search.)
+	-f <modulename>, --file <modulename>
+		Confine the search to the named file(s).
+		(Usually useful only after a previous search.)
 	-h, --help
 		Display this usage message.
 	-j <num-jobs>, --jobs <num-jobs>
 		Run using <num-jobs> different parallel processes.
 	-m <mmake-args>, --mmake-args <mmake-args>
 		Pass <mmake-args> as options to \`mmake'.
+	-n, --negative-search
+		Look for the module that suppresses the bug, not causes it.
 	-o <filename>, --output-file <filename>
 		Output results to <filename>.
 	-r, --copy-runtime
 		Copy the runtime directory instead of linking it.
+		This is necessary if the test uses a compilation model option
+		that differs from the one used in the main runtime directory.
 	-t <testdir>, --test-dir <testdir>
 		Execute runtests from the named subdirectory of tests.
 "
+
+set -x
 
 bootcheck=""
 compile_only=""
@@ -42,15 +54,28 @@ mmake_opts=""
 outfile=""
 copy_runtime=false
 testdirs=""
+negative=false
+alldirs=""
+allmodules=""
 
 while [ $# -gt 0 ]; do
 	case "$1" in
 
 	-b|--no-bootcheck)
-		bootcheck="-b"; shift ;;
+		bootcheck="-b" ;;
 
 	-c|--compile-only)
-		compile_only="-c"; shift ;;
+		compile_only="-c" ;;
+
+	-d|--dir)
+		alldirs="$2"; shift ;;
+	-d*)
+		alldirs="` expr $1 : '-d\(.*\)' `"; ;;
+
+	-f|--file)
+		allmodules="$allmodules $2"; shift ;;
+	-f*)
+		allmodules="$allmodules ` expr $1 : '-f\(.*\)' `"; ;;
 
 	-h|--help)
 		echo "$usage"
@@ -66,6 +91,9 @@ while [ $# -gt 0 ]; do
 	-m|--mmake)
 		mmake_opts="$mmake_opts $2"; shift ;;
 
+	-n|--negative-search)
+		negative=true ;;
+
 	-o|--output-file)
 		outfile="-o $2"; shift ;;
 	-o*)
@@ -77,23 +105,30 @@ while [ $# -gt 0 ]; do
 	-t|--test-dir)
 		testdirs="$testdirs -t$2"; shift ;;
 	-t*)
-		testdirs="$testdirs ` expr $1 : '-t\(.*\)' `"; ;;
+		testdirs="$testdirs ` expr $1 : '-t\(.*\)' `" ;;
 
-	--)	
-		shift; break ;;
 	-*)
 		echo "$0: unknown option \`$1'" 1>&2
 		echo "$usage" 1>&2
 		exit 1 ;;
+
 	*)
-		break ;;
+		echo "$usage" 1>&2
+		exit 1 ;;
 	esac
 	shift
 done
 
-root=`/bin/pwd`
-PATH=$root/tools:$PATH
-export PATH
+if test "$negative" = true
+then
+	base=bad
+	trial=ok
+	expected=failure
+else
+	base=ok
+	trial=bad
+	expected=success
+fi
 
 if test -d stage2.ok -a -d stage2.bad
 then
@@ -105,44 +140,50 @@ fi
 
 echo "starting at `date`"
 
+root=`/bin/pwd`
+PATH=$root/tools:$PATH
+export PATH
+
 [ -d stage2 ] || mkdir stage2
 /bin/rm -fr stage2/*
+set +x
+echo linking stage 2... 1>&2
 cd stage2
 mkdir compiler
 cd compiler
-ln -s ../../compiler/*.m .
-ln -s ../../compiler/Mmake* .
-cd ..
+ln -s $root/compiler/*.m .
+cp $root/compiler/Mmake* .
+cd $root/stage2
 mkdir library
 cd library
-ln -s ../../library/*.m .
-ln -s ../../library/*.nl .
-ln -s ../../library/Mmake* .
-ln -s ../../library/library.init .
-cd ..
+ln -s $root/library/*.m .
+# ln -s $root/library/*.nl .
+ln -s $root/library/library.init .
+cp $root/library/Mmake* .
+cd $root/stage2
 if test "$copy_runtime" = "true"
 then
 	mkdir runtime
 	cd runtime
-	ln -s ../../runtime/*.h .
-	ln -s ../../runtime/*.c .
-	ln -s ../../runtime/*.mod .
-	ln -s ../../runtime/*.in .
-	ln -s ../../runtime/Mmake* .
-	ln -s ../../runtime/machdeps .
-	cd ..
+	ln -s $root/runtime/*.h .
+	ln -s $root/runtime/*.c .
+	ln -s $root/runtime/*.mod .
+	ln -s $root/runtime/*.in .
+	ln -s $root/runtime/machdeps .
+	cp $root/runtime/Mmake* .
+	cd $root/stage2
 else
-	ln -s ../runtime .
+	ln -s $root/runtime .
 fi
-ln -s ../boehm_gc .
-ln -s ../doc .
-ln -s ../scripts .
-ln -s ../util .
-ln -s ../profiler .
-ln -s ../conf* .
+ln -s $root/boehm_gc .
+ln -s $root/doc .
+ln -s $root/scripts .
+ln -s $root/util .
+ln -s $root/profiler .
+ln -s $root/conf* .
 rm -f config*.log
-cp ../stage2.ok/Mmake* .
-cd ..
+cp $root/stage2.ok/Mmake* .
+cd $root
 
 # We don't copy the .d files. This prevents mmake from trying to remake any
 # of the .c and .o files, which we provide in the form they should be used.
@@ -158,75 +199,151 @@ cp stage2.ok/compiler/*.int stage2/compiler
 cp stage2.ok/compiler/*.int2 stage2/compiler
 cp stage2.ok/compiler/*.date stage2/compiler
 
-echo testing whether the stage2.bad library works
-
-cp stage2.bad/library/*.[co] stage2/library
-cp stage2.ok/compiler/*.[co] stage2/compiler
-
 set -x
 
-if binary_step $compile_only $jfactor -m "$mmake_opts" $outfile $bootcheck $testdirs
+if test "$copy_runtime" = "true"
 then
-	problemdir=compiler
-else
-	problemdir=library
+	if (cd stage2 ; mmake $mmake_opts $jfactor runtime)
+	then
+		echo "building of stage 2 runtime successful"
+	else
+		echo "building of stage 2 runtime not successful"
+		exit 1
+	fi
 fi
 
-echo "problem seems to be in the $problemdir directory"
+/bin/rm -f stage3/Mmake*
+cp $root/stage2.ok/Mmake* stage3
 
-# start out with all files in stage2 coming from stage2.ok
+if test "$alldirs" = ""
+then
+	echo testing whether the stage2.bad library works
 
-cp stage2.ok/library/*.[co] stage2/library
+	set +x
+	echo linking stage2/library from stage2.bad/library 1>&2
+	cp stage2.bad/library/*.[co] stage2/library
+	echo linking stage2/compiler from stage2.ok/compiler 1>&2
+	cp stage2.ok/compiler/*.[co] stage2/compiler
+	set -x
+
+	if test "$negative" = true
+	then
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			testeddir=library
+		else
+			testeddir=compiler
+		fi
+		echo "solution seems to be in the $testeddir directory"
+	else
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			testeddir=compiler
+		else
+			testeddir=library
+		fi
+		echo "problem seems to be in the $testeddir directory"
+	fi
+else
+	testeddir=$alldirs
+	if test ! -d stage2/$testeddir
+	then
+		echo $stage2/$testeddir does not exist
+		exit 1
+	fi
+fi
+
+# start out with all files in stage2 coming from stage2.$base
+
+set +x
+echo linking stage2 from stage2.$base 1>&2
+cp stage2.$base/library/*.[co] stage2/library
+cp stage2.$base/compiler/*.[co] stage2/compiler
+set -x
 
 # find the set of candidate modules
 
-cd stage2/$problemdir
-allfiles=`sub X.c X *.c`
-cd ../..
+if test "$allmodules" = ""
+then
+	cd stage2/$testeddir
+	allmodules=`sub X.c X *.c`
+	cd $root
+else
+	for module in $allmodules
+	do
+		if test ! -f stage2/$testeddir/$module.c
+		then
+			echo $stage2/$testeddir/$module.c does not exist
+			exit 1
+		fi
+	done
+fi
 
-doubtful="$allfiles"
+doubtful="$allmodules"
 tested=`half $doubtful`
 knowngood=
 
 while test "$tested" != ""
 do
-	# at this point, all the files in stage2 should be from stage2.ok
+	# at this point, all the files in stage2 should be from stage2.$base
 
 	echo "doubtful modules: $doubtful"
 	echo "testing modules:  $tested"
 
 	for module in $tested
 	do
-		cp stage2.bad/$problemdir/$module.[co] stage2/$problemdir
+		cp stage2.$trial/$testeddir/$module.[co] stage2/$testeddir
 	done
 
-	if binary_step $compile_only $jfactor -m "$mmake_opts" $outfile $bootcheck $testdirs
+	if test "$negative" = true
 	then
-		echo "test succeeded"
-		knowngood="$knowngood $tested"
-		newdoubtful=""
-		for module in $doubtful
-		do
-			if not appears $module $tested
-			then
-				newdoubtful="$newdoubtful $module"
-			fi
-		done
-		doubtful="$newdoubtful"
-		lasttest=success
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			echo "test succeeded"
+			lasttest=success
+			doubtful="$tested"
+		else
+			echo "test failed"
+			lasttest=failure
+			newdoubtful=""
+			for module in $doubtful
+			do
+				if not appears $module $tested
+				then
+					newdoubtful="$newdoubtful $module"
+				fi
+			done
+			doubtful="$newdoubtful"
+		fi
 	else
-		echo "test failed"
-		doubtful="$tested"
-		lasttest=failure
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			echo "test succeeded"
+			lasttest=success
+			knowngood="$knowngood $tested"
+			newdoubtful=""
+			for module in $doubtful
+			do
+				if not appears $module $tested
+				then
+					newdoubtful="$newdoubtful $module"
+				fi
+			done
+			doubtful="$newdoubtful"
+		else
+			echo "test failed"
+			lasttest=failure
+			doubtful="$tested"
+		fi
 	fi
 
 	for module in $tested
 	do
-		cp stage2.ok/$problemdir/$module.[co] stage2/$problemdir
+		cp stage2.$base/$testeddir/$module.[co] stage2/$testeddir
 	done
 
 	tested=`half $doubtful`
-	if test "$tested" = "" -a "$lasttest" = success
+	if test "$tested" = "" -a "$lasttest" = "$expected"
 	then
 		tested="$doubtful"
 	fi
@@ -234,41 +351,43 @@ done
 
 if test "$doubtful" = ""
 then
-	echo "cannot find the problem; all modules seem ok"
+	echo "cannot find the problem; all modules behave as expected"
 	exit 1
 fi
 
 module=`echo $doubtful | tr -d ' '`
-# arg $module
 
-echo "there is a problem in $problemdir/$module"
-echo "the modules known to be ok are: $knowngood"
+if test "$negative" = false
+then
+	echo "the modules known to be ok are: $knowngood"
+fi
+echo "there is a problem in $testeddir/$module"
 echo
 
-okcnt=`egrep '^END_MODULE' stage2.ok/$problemdir/$module.c | wc -l`
-badcnt=`egrep '^END_MODULE' stage2.bad/$problemdir/$module.c | wc -l`
+basecnt=`egrep '^END_MODULE' stage2.$base/$testeddir/$module.c | wc -l`
+trialcnt=`egrep '^END_MODULE' stage2.$trial/$testeddir/$module.c | wc -l`
 
-if test $okcnt -ne $badcnt
+if test $basecnt -ne $trialcnt
 then
-	okcnt=`echo $okcnt | tr -d ' '`
-	badcnt=`echo $badcnt | tr -d ' '`
+	basecnt=`echo $basecnt | tr -d ' '`
+	trialcnt=`echo $trialcnt | tr -d ' '`
 
 	echo "the two versions of the problem module"
 	echo "differ in the number of C modules they have"
-	echo "ok version: $okcnt vs bad version: $badcnt"
+	echo "$base version: $basecnt vs $trial version: $trialcnt"
 	exit 1
 fi
 
-for dir in ok bad
+for dir in $base $trial
 do
-	cd stage2.$dir/$problemdir
-	divide $module.c $okcnt
-	cd ../..
+	cd stage2.$dir/$testeddir
+	divide $module.c $basecnt
+	cd $root
 done
 
 doubtful=
 i=0
-while test $i -le $okcnt
+while test $i -le $basecnt
 do
 	doubtful="$doubtful $i"
 	i=`expr $i + 1`
@@ -282,45 +401,78 @@ do
 	echo "doubtful: $doubtful"
 	echo "testing:  $tested"
 
-	assemble $problemdir $module $okcnt $tested
-	cd stage2/$problemdir
+	assemble $base $trial $testeddir $module $basecnt $tested
+	cd stage2/$testeddir
 	/bin/rm $module.o
 	mmake $module.o
-	cd ../..
+	cd $root
 
-	if binary_step $compile_only $jfactor -m "$mmake_opts" $outfile $bootcheck $testdirs
+	if test "$negative" = true
 	then
-		echo "test succeeded"
-		knowngood="$knowngood $tested"
-		newdoubtful=""
-		for part in $doubtful
-		do
-			if not appears $part $tested
-			then
-				newdoubtful="$newdoubtful $part"
-			fi
-		done
-		doubtful="$newdoubtful"
-		lasttest=success
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			echo "test succeeded"
+			lasttest=success
+			doubtful="$tested"
+		else
+			echo "test failed"
+			lasttest=failure
+			newdoubtful=""
+			for part in $doubtful
+			do
+				if not appears $part $tested
+				then
+					newdoubtful="$newdoubtful $part"
+				fi
+			done
+			doubtful="$newdoubtful"
+		fi
 	else
-		echo "test failed"
-		doubtful="$tested"
-		lasttest=failure
+		if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+		then
+			echo "test succeeded"
+			lasttest=success
+			knowngood="$knowngood $tested"
+			newdoubtful=""
+			for part in $doubtful
+			do
+				if not appears $part $tested
+				then
+					newdoubtful="$newdoubtful $part"
+				fi
+			done
+			doubtful="$newdoubtful"
+		else
+			echo "test failed"
+			lasttest=failure
+			doubtful="$tested"
+		fi
 	fi
 
 	tested=`half $doubtful`
-	if test "$tested" = "" -a "$lasttest" = success
+	if test "$tested" = "" -a "$lasttest" = "$expected"
 	then
 		tested="$doubtful"
 	fi
 done
 
-echo "the parts known to be ok are: $knowngood"
-echo "there is a problem in $problemdir/$module.c.part.$doubtful"
+if test "$doubtful" = ""
+then
+	echo "cannot find the problem; all parts behave as expected"
+	exit 1
+fi
+
+doubtful=`echo $doubtful | tr -d ' '`
+
+if test "$negative" = false
+then
+	echo "the parts known to be ok are: $knowngood"
+fi
+echo "there is a problem in $testeddir/$module.c.part.$doubtful"
 echo "the difference is:"
 echo
 
-diff -u stage2.ok/$problemdir/$module.c.part.$doubtful stage2.bad/$problemdir/$module.c.part.$doubtful
+diff -u stage2.$base/$testeddir/$module.c.part.$doubtful stage2.$trial/$testeddir/$module.c.part.$doubtful
 
 echo
 echo "finishing at `date`"
diff --git a/tools/linear b/tools/linear
--- a/tools/linear
+++ b/tools/linear
@@ -21,6 +21,12 @@ Options:
 		Do not perform a bootcheck; check only the tests directory.
 	-c, --compile-only
 		Compile only. Do not compare stage2.ok and stage3.
+	-d <dirname>, --dir <dirname>
+		Confine the search to one directory, library or compiler.
+		(Usually useful only after a previous search.)
+	-f <filename>, --file <filename>
+		Confine the search to the named file(s).
+		(Usually useful only after a previous search.)
 	-h, --help
 		Display this usage message.
 	-j <num-jobs>, --jobs <num-jobs>
@@ -45,6 +51,8 @@ outfile=""
 copy_runtime=false
 testdirs=""
 negative=false
+alldirs="library compiler"
+allmodules=""
 
 while [ $# -gt 0 ]; do
 	case "$1" in
@@ -55,6 +63,16 @@ while [ $# -gt 0 ]; do
 	-c|--compile-only)
 		compile_only="-c" ;;
 
+	-d|--dir)
+		alldirs="$2"; shift ;;
+	-d*)
+		alldirs="` expr $1 : '-d\(.*\)' `"; ;;
+
+	-f|--file)
+		allmodules="$2"; shift ;;
+	-f*)
+		allmodules="` expr $1 : '-f\(.*\)' `"; ;;
+
 	-h|--help)
 		echo "$usage"
 		exit 0 ;;
@@ -64,7 +82,7 @@ while [ $# -gt 0 ]; do
 	-j*)
 		jfactor="-j` expr $1 : '-j\(.*\)' `" ;;
 	--jobs*)
-		jfactor="--jobs` expr $1 : '--jobs\(.*\)' `" ;;
+		jfactor="--jobs ` expr $1 : '--jobs\(.*\)' `" ;;
 
 	-m|--mmake)
 		mmake_opts="$mmake_opts $2"; shift ;;
@@ -126,40 +144,40 @@ export PATH
 /bin/rm -fr stage2/*
 cd stage2
 mkdir compiler
-cd compiler
-ln -s ../../compiler/*.m .
-cp ../../compiler/Mmake* .
-cd ..
+cd $root/stage2/compiler
+ln -s $root/compiler/*.m .
+cp $root/compiler/Mmake* .
+cd $root/stage2
 mkdir library
 cd library
-ln -s ../../library/*.m .
-# ln -s ../../library/*.nl .
-ln -s ../../library/library.init .
-cp ../../library/Mmake* .
-cd ..
+ln -s $root/library/*.m .
+# ln -s $root/library/*.nl .
+ln -s $root/library/library.init .
+cp $root/library/Mmake* .
+cd $root/stage2
 if test "$copy_runtime" = "true"
 then
 	mkdir runtime
 	cd runtime
-	ln -s ../../runtime/*.h .
-	ln -s ../../runtime/*.c .
-	ln -s ../../runtime/*.mod .
-	ln -s ../../runtime/*.in .
-	ln -s ../../runtime/machdeps .
-	cp ../../runtime/Mmake* .
-	cd ..
+	ln -s $root/runtime/*.h .
+	ln -s $root/runtime/*.c .
+	ln -s $root/runtime/*.mod .
+	ln -s $root/runtime/*.in .
+	ln -s $root/runtime/machdeps .
+	cp $root/runtime/Mmake* .
+	cd $root/stage2
 else
-	ln -s ../runtime .
+	ln -s $root/runtime .
 fi
-ln -s ../boehm_gc .
-ln -s ../doc .
-ln -s ../scripts .
-ln -s ../util .
-ln -s ../profiler .
-ln -s ../conf* .
+ln -s $root/boehm_gc .
+ln -s $root/doc .
+ln -s $root/scripts .
+ln -s $root/util .
+ln -s $root/profiler .
+ln -s $root/conf* .
 rm -f config*.log
-cp ../stage2.ok/Mmake* .
-cd ..
+cp $root/stage2.ok/Mmake* .
+cd $root
 
 # We don't copy the .d files. This prevents mmake from trying to remake any
 # of the .c and .o files, which we provide in the form they should be used.
@@ -178,17 +196,32 @@ cp stage2.ok/compiler/*.date stage2/compiler
 cp stage2.$base/library/*.[co] stage2/library
 cp stage2.$base/compiler/*.[co] stage2/compiler
 
+if test "$copy_runtime" = "true"
+then
+	if (cd stage2 ; mmake $mmake_opts $jfactor runtime)
+	then
+		echo "building of stage 2 runtime successful"
+	else
+		echo "building of stage 2 runtime not successful"
+		exit 1
+	fi
+fi
+
 set -x
 
 normal=
 unusual=
+unusualparts=
 
-for testeddir in library compiler
+for testeddir in $alldirs
 do
-	# find the set of candidate modules
-	cd stage2/$testeddir
-	allmodules=`sub X.c X *.c`
-	cd ../..
+	# find the set of modules to search, if not given on command line
+	if test "$allmodules" = ""
+	then
+		cd stage2/$testeddir
+		allmodules=`sub X.c X *.c`
+		cd $root
+	fi
 
 	for testedmodule in $allmodules
 	do
@@ -213,6 +246,60 @@ do
 			normal="$normal $testeddir/$testedmodule"
 		else
 			unusual="$unusual $testeddir/$testedmodule"
+
+			basecnt=`egrep '^END_MODULE' stage2.$base/$testeddir/$testedmodule.c | wc -l`
+			trialcnt=`egrep '^END_MODULE' stage2.$trial/$testeddir/$testedmodule.c | wc -l`
+
+			if test $basecnt -ne $trialcnt
+			then
+				basecnt=`echo $basecnt | tr -d ' '`
+				trialcnt=`echo $trialcnt | tr -d ' '`
+
+				echo "the two versions of the unusual module"
+				echo "differ in the number of C modules they have"
+				echo "$base version: $basecnt vs $trial version: $trialcnt"
+				exit 1
+			fi
+
+			for dir in $base $trial
+			do
+				cd stage2.$dir/$testeddir
+				divide $testedmodule.c $basecnt
+				cd $root
+			done
+
+			allparts=
+			i=0
+			while test $i -le $basecnt
+			do
+				allparts="$allparts $i"
+				i=`expr $i + 1`
+			done
+
+			for testedpart in $allparts
+			do
+				echo testing part $testedpart in `/bin/pwd`
+				assemble $base $trial $testeddir $testedmodule $basecnt $testedpart
+
+				cd stage2/$testeddir
+				/bin/rm $testedmodule.o
+				mmake $testedmodule.o
+				cd $root
+
+				if binary_step $bootcheck $compile_only $jfactor -m "$mmake_opts" $outfile $testdirs
+				then
+					echo "test succeeded"
+					lasttest=success
+				else
+					echo "test failed"
+					lasttest=failure
+				fi
+
+				if test "$lasttest" != "$expected"
+				then
+					unusualparts="$unusualparts $testeddir/$testedmodule.part.$testedpart"
+				fi
+			done
 		fi
 
 		cp stage2.$base/$testeddir/$testedmodule.[co] stage2/$testeddir
@@ -225,4 +312,8 @@ echo $normal
 echo "modules whose stage.$trial versions do not behave as expected:"
 echo $unusual
 
+echo "module parts whose stage.$trial versions do not behave as expected:"
+echo $unusualparts
+
+echo "finishing at `date`"
 exit 0
