<overview or general description of changes>
Estimated hours taken: 1

<overview or general description of changes>

<directory>/<file>:
	<detailed description of changes>

diff --git a/tools/binary_step b/tools/binary_step
--- a/tools/binary_step
+++ b/tools/binary_step
@@ -1,8 +1,20 @@
 #!/bin/sh
+# Test the stage2 directory to see whether it passes
+# a bootstrap check and/or a check using the tests directory.
+# If stage2 passes, binary_step returns an exit status of 0 (true);
+# if it fails, binary_step returns an exit status of 1 (false).
+#
+# binary_step remakes the archive in stage2/library and the executable
+# in stage2/compiler. In the intended use, the binary script sets up
+# these directories so that these actions cause no recompilations,
+# either Mercury to C or C to object, only linking. Other uses probably
+# won't work.
 
 usage="\
 Usage: $0 [options]
 Options:
+	-b, --no-bootcheck
+		Do not perform a bootcheck; check only the tests directory.
 	-c, --compile-only
 		Compile only. Do not compare stage2.ok and stage3.
 	-h, --help
@@ -13,18 +25,29 @@ Options:
 		Pass <mmake-args> as options to \`mmake'.
 	-o <filename>, --output-file <filename>
 		Output results to <filename>.
+	-t <testdir>, --test-dir <testdir>
+		Execute runtests from the named subdirectory of tests.
 "
 
+set -x
+
+alltestdirs="benchmarks general hard_coded invalid valid warnings"
+
+bootcheck="true"
 compile_only="false"
 jfactor=""
 mmake_opts=""
-outfile=""
+outfile="DIFF.BINARY"
+testdirs=""
 
 while [ $# -gt 0 ]; do
 	case "$1" in
 
+	-b|--no-bootcheck)
+		bootcheck="false" ;;
+
 	-c|--compile-only)
-		compile_only="true"; shift ;;
+		compile_only="true" ;;
 
 	-h|--help)
 		echo "$usage"
@@ -44,6 +67,33 @@ while [ $# -gt 0 ]; do
 		outfile="$2"; shift ;;
 	-o*)
 		outfile="` expr $1 : '-o\(.*\)' `"; ;;
+
+	-t|--test-dir)
+		testdir="$2"; shift
+		if test -d tests/$testdir
+		then
+			testdirs="$testdirs $testdir"
+		else
+			if "$testdir" = "all"
+			then
+				testdirs="$alltestdirs"
+			else
+				echo "tests has no subdirectory named $testdir"
+			fi
+		fi ;;
+	-t*)
+		testdir="` expr $1 : '-t\(.*\)' `"
+		if test -d tests/$testdir
+		then
+			testdirs="$testdirs $testdir"
+		else
+			if "$testdir" = "all"
+			then
+				testdirs="$alltestdirs"
+			else
+				echo "tests has no subdirectory named $testdir"
+			fi
+		fi ;;
 
 	--)	
 		shift; break ;;
@@ -71,6 +121,8 @@ export MMAKE_DIR
 
 # Ensure that mmake will not disturb the .o and .c files placed there by binary
 
+set +x
+
 touch stage2/library/*.c
 touch stage2/compiler/*.c
 
@@ -83,6 +135,8 @@ touch stage2/compiler/*.o
 
 /bin/rm -f stage2/library/libmercury.a stage2/library/libmercury.so
 /bin/rm -f stage2/compiler/mercury_compile
+
+set -x
 
 # the `RM_C=:' ensures that the `.c' files do not get deleted
 
@@ -110,65 +164,80 @@ export MERCURY_COMPILER
 MERCURY_INT_DIR=$root/stage3/library
 export MERCURY_INT_DIR
 
-# Rebuild the stage3 library and compiler from scratch
-
-/bin/rm -f stage3/library/*.c
-/bin/rm -f stage3/compiler/*.c
-
-if (cd stage3 ; mmake $mmake_opts depend_library depend_compiler)
+if "$bootcheck" = true
 then
-	echo "building of stage 3 dependencies successful"
-else
-	echo "building of stage 3 dependencies not successful"
-	exit 1
+
+	# Rebuild the stage3 library and compiler from scratch
+
+	/bin/rm -f stage3/library/*.c
+	/bin/rm -f stage3/compiler/*.c
+
+	if (cd stage3 ; mmake $mmake_opts depend_library depend_compiler)
+	then
+		echo "building of stage 3 dependencies successful"
+	else
+		echo "building of stage 3 dependencies not successful"
+		exit 1
+	fi
+
+	MMAKE_VPATH=.
+	export MMAKE_VPATH
+	MMAKE_DIR=../scripts
+	export MMAKE_DIR
+
+	if (cd stage3/library ; mmake -S $mmake_opts $jfactor cs)
+	then
+		echo "building of stage 3 library successful"
+	else
+		echo "building of stage 3 library not successful"
+		exit 1
+	fi
+
+	if (cd stage3/compiler ; mmake -S $mmake_opts $jfactor cs)
+	then
+		echo "building of stage 3 compiler successful"
+	else
+		echo "building of stage 3 compiler not successful"
+		exit 1
+	fi
+
+	if test "$compile_only" = false
+	then
+		founddiff=false
+		cat /dev/null > $outfile
+		for dir in library compiler
+		do
+			for file in stage2.ok/$dir/*.c
+			do
+				stage3file="stage3/$dir/`basename $file`"
+				diff -u $file $stage3file >> $outfile ||
+					founddiff="true"
+			done
+		done
+
+		if test $exit_status -ne 0
+		then
+			echo "error - stage2.ok and stage3 differ!"
+		else
+			echo "stage2.ok and stage3 compare ok"
+		fi
+
+		if "$founddiff" = true
+		then
+			exit 1
+		fi
+	fi
 fi
 
-MMAKE_VPATH=.
-export MMAKE_VPATH
-MMAKE_DIR=../scripts
-export MMAKE_DIR
-
-if (cd stage3/library ; mmake -S $mmake_opts $jfactor cs)
-then
-	echo "building of stage 3 library successful"
-else
-	echo "building of stage 3 library not successful"
-	exit 1
-fi
-
-if (cd stage3/compiler ; mmake -S $mmake_opts $jfactor cs)
-then
-	echo "building of stage 3 compiler successful"
-else
-	echo "building of stage 3 compiler not successful"
-	exit 1
-fi
-
-if test "$compile_only" = "true"
-then
-	exit 0
-fi
-
-exit_status=0
-
-exec 3>&1		# save stdout in fd 3
-if [ -n "$outfile" ]
-then
-	exec > "$outfile"	# redirect stdout to $outfile
-fi
-
-for dir in library compiler; do
-	for file in stage2.ok/$dir/*.c; do
-		diff -u $file stage3/$dir/`basename $file` ||
-			exit_status=1
-	done
+for testdir in $testdirs
+do
+	if (cd tests/$testdir; runtests)
+	then
+		echo "tests in the $testdir directory successful"
+	else
+		echo "tests in the $testdir directory not successful"
+		exit 1
+	fi
 done
 
-exec >&3		# restore stdout from fd 3
-if [ $exit_status -ne 0 ]; then
-	echo "error - stage 2 and stage 3 differ!"
-else
-	echo "stage 2 and stage 3 compare ok"
-fi
-
-exit $exit_status
+exit 0
