A first implementation of the inter-module analysis framwork.
Estimated hours taken: 80
Branches: main

A first implementation of the inter-module analysis framwork.
Currently only unused argument analysis is supported.

The current inter-module analysis scheme using `.trans_opt' files
has some major limitations. The compilation dependencies introduced
by `.trans_opt' files are too complicated for Mmake without major
limitations on which modules can use the contents of which `.trans_opt'
files. Also, the `.trans_opt' file system only computes greatest fixpoints,
which is often too weak to find opportunities for optimization.
A better solution is to provide a library which manually handles
the dependencies introduced by inter-module analysis, and can deal with
the complications introduced by cyclic module dependencies.

TODO:
- support other analyses, e.g. termination, type specialization
- dependency tracking and invalidation after source modifications
- garbage collection of unused versions
- least fixpoint analyses

analysis/Mmakefile:
analysis/mer_analysis.m:
analysis/analysis.m:
analysis/analysis.file.m:
	The analysis library.

analysis/README:
	Description and design documentation.

Mmake.workspace:
Mmakefile:
compiler/Mmakefile:
tools/bootcheck:
	Link the analysis library into mercury_compile.

compiler/hlds_module.m:
	Store analysis information in the module_info.

compiler/options.m:
doc/user_guide.texi:
	Add an option `--intermodule-analysis'.

compiler/mercury_compile.m:
	Call the analysis library to write the gathered
	information at the end of a compilation.

compiler/unused_args.m:
	Call the analysis library to retrieve information
	about imported procedures. This replaces code which
	used the `.opt' files.

	Change the names created for unused arguments procedures
	to include the arguments removed, rather than a sequence
	number. I think Zoltan is working on a change to name
	mangling, so I haven't updated the demangler.

compiler/prog_util.m:
	Generate the new predicate names for unused_args.m.

library/std_util.m:
	Add a polymorphic version of unit, which is useful
	for binding type variables.

compiler/modules.m:
scripts/Mmake.vars.in:
	Clean up files created by the analysis framework
	in `mmake realclean'.

util/mdemangle.c:
profiler/demangle.m:
	Document the change in the name mangling of procedures with
	unused arguments.

configure.in:
	Check for state variables and fixes for some typeclass bugs.

tests/warnings/Mmakefile:
tests/warnings/unused_args_analysis.{m,exp}:
	Test case.

diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -495,6 +495,13 @@ then
 		cp $root/browser/Mmake* $root/browser/Mercury.options .
 		$LN_S $root/browser/$BROWSER_LIB_NAME.init .
 		cd $root/stage2
+		mkdir analysis
+		cd analysis
+		$LN_S $root/analysis/*.m .
+		cp $root/analysis/Mmake* $root/analysis/Mercury.options .
+		$LN_S $root/analysis/$ANALYSIS_LIB_NAME.init .
+
+		cd $root/stage2
 		if $copy_runtime
 		then
 			# Remove symbolic link to the stage 1 runtime
@@ -616,7 +623,8 @@ then
 		fi
 
 		if (cd stage2 && $MMAKE $mmake_opts dep_library dep_browser \
-			dep_compiler dep_profiler dep_deep_profiler)
+			dep_analysis dep_compiler dep_profiler \
+			dep_deep_profiler)
 		then
 			echo "building of stage 2 dependencies successful"
 		else
@@ -645,6 +653,14 @@ then
 			echo "building of stage 2 trace successful"
 		else
 			echo "building of stage 2 trace not successful"
+			exit 1
+		fi
+
+		if (cd stage2 && $MMAKE $mmake_opts $jfactor analysis)
+		then
+			echo "building of stage 2 analysis successful"
+		else
+			echo "building of stage 2 analysis not successful"
 			exit 1
 		fi
 
@@ -794,6 +810,12 @@ then
 	cp $root/browser/Mmake* $root/browser/Mercury.options .
 	$LN_S $root/browser/$BROWSER_LIB_NAME.init .
 	cd $root/stage3
+	mkdir analysis
+	cd analysis
+	$LN_S $root/analysis/*.m .
+	cp $root/analysis/Mmake* $root/analysis/Mercury.options .
+	$LN_S $root/analysis/$ANALYSIS_LIB_NAME.init .
+	cd $root/stage3
 	$LN_S $root/boehm_gc .
 	$LN_S $root/mps_gc .
 	$LN_S $root/bindist .
@@ -834,7 +856,7 @@ then
 	fi
 
 	if (cd stage3 && $MMAKE $mmake_opts dep_library dep_browser \
-		dep_compiler)
+		dep_analysis dep_compiler)
 	then
 		echo "building of stage 3 dependencies successful"
 	else
@@ -892,6 +914,26 @@ then
 		fi
 	fi
 
+	if 	(cd stage3/analysis &&
+		$MMAKE $mmake_opts $jfactor all-ints &&
+		$MMAKE $mmake_opts $jfactor ${target_ext}s)
+	then
+		echo "building of stage 3 analysis successful"
+	else
+		echo "building of stage 3 analysis initially not successful"
+		df .
+		# try again, in case the failure cause was transient
+		if 	(cd stage3/analysis &&
+			$MMAKE $mmake_opts $jfactor all-ints &&
+			$MMAKE $mmake_opts $jfactor ${target_ext}s)
+		then
+			echo "building of stage 3 analysis successful"
+		else
+			echo "building of stage 3 analysis not successful"
+			exit 1
+		fi
+	fi
+
 	if (cd stage3/compiler && $MMAKE $mmake_opts $jfactor ${target_ext}s)
 	then
 		echo "building of stage 3 compiler successful"
@@ -923,7 +965,7 @@ then
 		exec > "$outfile"	# redirect stdout to $outfile
 	fi
 
-	for dir in library browser compiler; do
+	for dir in library browser analysis compiler; do
 		# `mmake cs' in the compiler directory doesn't build
 		# `top_level_init.c', so we only compare the `.c'
 		# files present in the stage3 directory.
diff --git a/tools/generate_index_html b/tools/generate_index_html
--- a/tools/generate_index_html
+++ b/tools/generate_index_html
@@ -16,10 +16,23 @@ BETA_RELEASE=0.11.1
 # matching the release numbers.
 shopt -s extglob
 
-INDEX=index.html.$HOST
+INDEX=index.html.$HOST.$$
+LOCKDIR=generate_index_html.lock
 handled_files=
 
-trap 'rm -f $INDEX; exit 1' 1 2 3 13 15
+# Lock the directory (this script may be invoked by test_mercury
+# on multiple machines at once).
+timeout=20
+retries=0
+until mkdir $LOCKDIR; do
+	case $retries in
+	    $timeout) 	echo "** $0: timed out" 1>&2; exit 1 ;;
+	esac
+	sleep 5
+	retries=`expr $retries + 1`
+done
+
+trap 'rm -rf $INDEX $LOCKDIR; exit 1' 1 2 3 13 15
 
     #
     # These are the standard locations for apache's icons
@@ -188,7 +201,7 @@ echo "$img_bak <a href=../>Parent Directory</a><br>" >> $INDEX
 #
 for file in *
 do
-	if [ -d $file ]
+	if [ -d $file -a $file != $LOCKDIR ]
 	then
 		(cd $file && generate_index_html)
 		echo "$img_dir <a href=$file/>$file/</a><br>" >> $INDEX
@@ -291,3 +304,4 @@ chgrp mercury $INDEX
 
 mv $INDEX index.html
 
+rmdir $LOCKDIR || { echo "** $0: error removing $LOCKDIR" 1>&2; exit 1; }
