Add some Mmake rules to the runtime and some code to tools/bootcheck
Estimated hours taken: 16

Add some Mmake rules to the runtime and some code to tools/bootcheck
so that we automatically check that the namespace remains clean.
Also add some `MR_' prefixes that Zoltan missed in his earlier change.

tools/bootcheck:
	Add an option, which is enabled by default, to
	build the check_namespace target in the runtime.

runtime/RESERVED_MACRO_NAMES:
	New file.  Contains a list of the macros names that
	don't start with `MR_' or the like.

runtime/Mmakefile:
	Change the rule for `check_headers' so that it checks for macros
	that don't occur in the RESERVED_MACRO_NAMES files, as well as not
	starting with `MR_' prefixes, and reports errors for such macros.
	Also add a rule for check_objs that checks whether the object
	files define any global symbols that don't have the right prefixes,
	and a rule `check_namespace' that does both of the above.

runtime/mercury_bootstrap.h:
	#include "mercury_types.h" and "mercury_float.h",
	to ensure that this header file is self-contained.
	Also make sure that all the old names are disabled if you
	compile with `-DMR_NO_BACKWARDS_COMPAT'.

runtime/mercury_context.c:
runtime/mercury_thread.h:
runtime/mercury_thread.c:
	Use `bool' rather than `MR_Bool' for the argument to
	MR_check_pending_contexts() and the return type of
	MR_init_thread(), since these are C bools, not Mercury
	bools, and there's no requirement that they have the
	same size as MR_Integer.

runtime/mercury_type_info.h:
runtime/mercury_deep_copy_body.h:
runtime/mercury_tabling.c:
library/std_util.m:
trace/mercury_trace_declarative.c:
trace/mercury_trace_external.c:
trace/mercury_trace_internal.c:
tests/hard_coded/existential_types_test.m:
	Add MR_ prefixes to UNIV_OFFSET_FOR_TYPEINFO and UNIV_OFFSET_FOR_VALUE.

trace/mercury_trace_external.c:
trace/mercury_trace_internal.c:
trace/mercury_trace_tables.c:
	Add MR_ prefixes to do_init_modules().

runtime/mercury_tabling.h:
runtime/mercury_tabling.c:
runtime/mercury_overflow.h:
runtime/mercury_debug.h:
	Add MR_ prefixes to table_*.

runtime/mercury_overflow.h:
runtime/mercury_debug.h:
	Add MR_ prefixes to IF().

runtime/mercury_context.h:
	Add MR_ prefixes to IF_MR_THREAD_SAFE().

runtime/mercury_engine.h:
	Add MR_ prefixes to IF_NOT_CONSERVATIVE_GC().

runtime/mercury_engine.h:
runtime/mercury_engine.c:
extras/aditi/aditi.m:
	Add MR_ prefixs to do_fail, do_redo, do_not_reached, etc.

compiler/trace.m:
compiler/fact_table.m:
compiler/llds_out.m:
	Add MR_ prefixes to the generated code.

diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -53,6 +53,8 @@ Options:
 		Do not run the bootstrap check; execute the test suite and/or
 		the extras only. This option requires a previous bootstrap
 		check to have left a working stage 2 directory.
+	--no-check-namespace
+		Don't build the check_namespace target in the runtime.
 	-t, --no-test-suite
 		By default, bootcheck will also run the test quite.
 		This option prevents that.
@@ -97,6 +99,7 @@ mmake_opts="-k"
 outfile=""
 runtests=true
 do_bootcheck=true
+check_namespace=true
 grade=
 test_grade=
 test_params=false
@@ -176,6 +179,9 @@ while [ $# -gt 0 ]; do
 
 	-n|--no-bootcheck)
 		do_bootcheck=false ;;
+
+	--no-check_namespace)
+		check_namespace=false ;;
 
 	-t|--no-test-suite)
 		runtests=false ;;
@@ -296,6 +302,8 @@ if test "$RMSTAGECMD" = ""
 then
 	RMSTAGECMD="/bin/rm -fr"
 fi
+
+#-----------------------------------------------------------------------------#
 
 if $do_bootcheck
 then
@@ -715,7 +723,7 @@ then
 
 	exec >&3		# restore stdout from fd 3
 	if [ $diff_status -ne 0 ]; then
-		echo "error - stage 2 and stage 3 differ!"
+		echo "** error - stage 2 and stage 3 differ!"
 	else
 		echo "stage 2 and stage 3 compare ok"
 		echo "removing stage 3..."
@@ -734,6 +742,8 @@ else
 	diff_status=0
 	echo "building of stages 1 and 2 skipped"
 fi
+
+#-----------------------------------------------------------------------------#
 
 if test "$runtests" = "true" -o "$extras" = "true"
 then
@@ -798,6 +808,30 @@ then
 	PATH=$root/${stage2_insert}util:$root/${stage2_insert}scripts:$PATH
 	export PATH
 fi
+
+#-----------------------------------------------------------------------------#
+
+# build the check_namespace target in the runtime directory
+
+check_namespace_status=0
+if $check_namespace
+then
+	cd $root/${stage2_insert}runtime
+	mmake $mmake_opts check_namespace || {
+		echo '** mmake check_namespace failed!'
+		# XXX Currently we just report the errors;
+		#     we don't yet actually return a non-zero status.
+		#     That's why the line below is commented out.
+		#     This is a transition measure until we're sure
+		#     that everything really is namespace-clean.
+		# check_namespace_status=1
+	}
+	cd $root
+fi
+
+#-----------------------------------------------------------------------------#
+
+# Run the tests in the tests/* directories
 
 test_status=0
 if $runtests
@@ -865,6 +899,10 @@ then
 	fi
 fi
 
+#-----------------------------------------------------------------------------#
+
+# Run the tests in the extras/* directories
+
 extras_status=0
 if $extras
 then
@@ -916,6 +954,8 @@ then
 	cd $root
 fi
 
+#-----------------------------------------------------------------------------#
+
 if test "$type_stats" != ""
 then
 	mv "$type_stats".save.$$ "$type_stats"
@@ -923,9 +963,12 @@ fi
 
 echo "finishing at `date`"
 
-if test "$diff_status" = 0 -a "$test_status" = 0 -a "$extras_status" = 0
+if test "$diff_status" = 0 -a "$test_status" = 0 -a "$extras_status" = 0 \
+	-a "$check_namespace_status" = 0
 then
 	exit 0
 else
 	exit 1
 fi
+
+#-----------------------------------------------------------------------------#
