Enforce namespace cleanliness in the library and browser directories
Estimated hours taken: 6
Branches: main

Enforce namespace cleanliness in the library and browser directories
as well as in the runtime and trace directories.

Mmake.common.in:
	Move the rules check_namespace here (they used to be in the Mmakefiles
	of the runtime and trace directories), together with the variables they
	need. Generalize them to also handle the needs of the browser, library
	and bytecode directories. The former two in particular need the
	ability to check automatically generated .mh files.

	Make all the rules used by check_namespace conditional on a macro
	that is defined by the Makefiles in all the directories that are
	checked for namespace cleanliness.

trace/Mmakefile:
runtime/Mmakefile:
	Replace the old rules for check_namespace, which are now in
	../Mmake.common.in, with the macros needed to control their behavior.

bytecode/Mmakefile:
	Add the macros needed to control the behavior of the rules for
	check_namespace.

	Move the lists of files to the start, before the include of
	../Mmake.common.

browser/Mmakefile:
library/Mmakefile:
	Add the macros needed to control the behavior of the rules for
	check_namespace.

runtime/RESERVED_MACRO_NAMES:
	Update comments, and delete obsolete exceptions.

browser/RESERVED_MACRO_NAMES:
library/RESERVED_MACRO_NAMES:
	New files to contain the exceptions from the naming scheme.

tools/bootcheck:
	Invoke "mmake check_namespace" in the library and browser directories
	as well as the runtime and the trace directories. Perform the
	invocation before we delete the object files we are checking for
	cleanliness.

	Clean up object files in all stage2 directories, not just the library,
	as soon as we can.

library/array.m:
library/builtin.m:
library/io.m:
library/time.m:
	Fix namespace violations.

diff --git a/tools/bootcheck b/tools/bootcheck
--- a/tools/bootcheck
+++ b/tools/bootcheck
@@ -54,15 +54,14 @@ Options:
 		that is not compatible with the standard one.
 	-p, --copy-profiler
 		Copy the profiler directory instead of linking it.
-		This is sometimes necessary for bootstrapping
-		changes.
+		This is sometimes necessary for bootstrapping changes.
 	-b-, --no-bootcheck
 		Do not run the bootstrap check; execute the test suite and/or
 		the extras only. This option requires a previous bootstrap
 		check to have left a working stage 2 directory.
 	--no-check-namespace
-		Don't build the check_namespace targets in the runtime
-		and trace directories.
+		Don't build the check_namespace targets in the runtime,
+		trace, browser and library directories.
 	-t-, --no-test-suite
 		By default, bootcheck will also run the test quite.
 		This option prevents that.
@@ -247,6 +246,7 @@ while [ $# -gt 0 ]; do
 		runtests=false ;;
 
 	--skip-stage-2)
+		keep_stage_2=true
 		mmake_stage_2=false ;;
 
 	-2|--keep-stage-2)
@@ -661,20 +661,75 @@ then
 		fi
 	fi
 
+	# Build the check_namespace target in the relevant directories.
+	# We want to do so before we delete any of the stage2 object files.
+
+	check_namespace_status=0
+	if $check_namespace
+	then
+		cd $root/stage2/runtime
+		mmake $mmake_opts check_namespace || {
+			echo '** mmake check_namespace failed in runtime!'
+			check_namespace_status=1
+		}
+		cd $root/stage2/trace
+		mmake $mmake_opts check_namespace || {
+			echo '** mmake check_namespace failed in trace!'
+			check_namespace_status=1
+		}
+		cd $root/stage2/library
+		mmake $mmake_opts check_namespace || {
+			echo '** mmake check_namespace failed in library!'
+			check_namespace_status=1
+		}
+		cd $root/stage2/browser
+		mmake $mmake_opts check_namespace || {
+			echo '** mmake check_namespace failed in browser!'
+			check_namespace_status=1
+		}
+		cd $root
+	fi
+
 	if $stop_after_stage_2
 	then
 		echo "stopping after building stage 2"
 		exit 0
 	fi
 
-	# We can remove the library object files now,
-	# but we will keep the compiler objects for a while longer
+	# We can now remove the object files from most stage2 directories,
+	# but we will keep the compiler objects for a while longer.
 	if $keep_objs
 	then
 		true
 	else
-		find $root/stage2/library -name "*.o" -print |
-		xargs /bin/rm -f
+		libdirs="library browser"
+		if $copy_profiler
+		then
+			profdirs="profiler deep_profiler"
+		else
+			profdirs=
+		fi
+		if $copy_runtime
+		then
+			rundirs="runtime trace"
+		else
+			rundirs=
+		fi
+
+		objdirs="$libdirs $profdirs $rundirs"
+		for rmdir in $objdirs
+		do
+			cd $root/stage2/$rmdir
+			/bin/rm -f *.o *.pic_o
+		done
+
+		for cleandir in runtime trace library browser
+		do
+			cd $root/stage2/$cleandir
+			mmake clean_check
+		done
+
+		cd $root
 	fi
 
 	MERCURY_COMPILER=$root/stage2/compiler/mercury_compile
@@ -935,26 +990,6 @@ then
 	# Set PATH for mkinit, mmc, mgnuc, ml etc
 	PATH=$root/${stage2_insert}util:$root/${stage2_insert}scripts:$PATH
 	export PATH
-fi
-
-#-----------------------------------------------------------------------------#
-
-# build the check_namespace target in the runtime directory
-
-check_namespace_status=0
-if $check_namespace
-then
-	cd $root/${stage2_insert}runtime
-	mmake $mmake_opts check_namespace || {
-		echo '** mmake check_namespace failed!'
-		check_namespace_status=1
-	}
-	cd $root/${stage2_insert}trace
-	mmake $mmake_opts check_namespace || {
-		echo '** mmake check_namespace failed!'
-		check_namespace_status=1
-	}
-	cd $root
 fi
 
 #-----------------------------------------------------------------------------#
