Commit to the new build_srcdist.
tools/build_srcdist:
    Delete the old build_srcdist, and rename build_srcdist2 as build_srcdist.
    Make it refer to the tar target designed for it, tar2, under its new name
    tar.

Mmakefile:
    Delete the old tar target (which worked with the old build_srcdist),
    and rename the old tar2 target (which works with the new build_srcdist)
    as just plain tar.

diff --git a/tools/build_srcdist b/tools/build_srcdist
--- a/tools/build_srcdist
+++ b/tools/build_srcdist
@@ -3,48 +3,60 @@
 #
 # This script builds the Mercury source distribution.
 #
+# After any options, this script expects exactly three arguments
+#
+# The first argument should be the path name of the Mercury workspace
+# that the distribution should be based on.
+#
+# The second argument should be name associated with the version.
+# The two usual forms of these names are rotd-yyyy-mm-dd for ROTDs
+# and yy.mm for major releases.
+#
+# The third is the absolute path name where the tar file containing
+# the Mercury source distribution should be put. To prevent surprises
+# when the tar file is unpacked, the name should end in
+# mercury-srcdist-VERSION.tar
+#
 
 set -e
 
-DATE=`date '+%Y-%m-%d'`
-ROTD_VERSION=rotd-${DATE}
-RELEASE_VERSION=${ROTD_VERSION}
 CC=gcc
-RUN=no
+TMPDIR=/tmp
 PARALLEL=1
+# We should set the default LEAVE_TMP_DIR to "no"
+# once this script has been in use for a while.
+LEAVE_TMP_DIR=yes
+UPDATE_VERSION_FILE=yes
 TAR=tar
 
 USAGE="\
-$0 [options]
+$0 [options] orig_ws version tar_file_name
 Options:
     -c CC
         Use CC as the C compiler.
-    -f
-        Without this option the build_srcdist script will not run;
-        it will just warn the user that it is destructive, and then exit.
+    -d
+        The directory in which to do work. It should be a directory intended
+        for short-lived files, such as /tmp or /var/tmp.
     -h
         Output this help message and exit.
     -j N
         Run N jobs in parallel.
+    -l
+        Leave the temporary directory as it was when done.
     -n
         Do not update the VERSION file.
-    -r
-        Use a ROTD style version number with today's date
-        (this is the default).
     -t TAR
         Use TAR as the archiving utility (default: tar).
-    -v VER
-        Use VER as the version number.
 "
 
-while getopts "c:fhj:nrt:v:" OPT
+while getopts "c:d:hj:lnt:" OPT
 do
     case "${OPT}" in
         c)
             CC=${OPTARG}
             ;;
-        f)
-            RUN=yes
+        d)
+            TMPDIR=${OPTARG}
             ;;
         h)
             echo "${USAGE}"
@@ -53,17 +65,14 @@ do
         j)
             PARALLEL=${OPTARG}
             ;;
-        n)
-            RELEASE_VERSION=""
+        l)
+            LEAVE_TMP_DIR=yes
             ;;
-        r)
-            RELEASE_VERSION=${ROTD_VERSION}
+        n)
+            UPDATE_VERSION_FILE=no
             ;;
         t)
             TAR=${OPTARG}
-            ;;
-        v)
-            RELEASE_VERSION=${OPTARG}
             ;;
         ?)
             echo "${USAGE}"
@@ -77,45 +86,73 @@ do
     esac
 done
 
-if test ! -d .git
+shift `expr ${OPTIND} - 1`
+
+if test "$#" != 3
 then
-    echo "Error: $0 must be called from the root directory"
-    echo "of a Mercury git workspace."
+    echo "${USAGE}"
+    exit 1
+fi
+
+orig_ws="$1"
+version="$2"
+tar_file_name="$3"
+
+if test ! -d "${orig_ws}"
+then
+    echo "Error: ${orig_ws} is not a directory"
     exit 2
 fi
 
-if test "${RUN}" = "no"
+if test ! -d "${orig_ws}/.git"
 then
-    echo "Warning: this script is destructive."
-    echo "Specifically, it will 'git clean' your workspace."
-    echo "If you are okay with this and want to proceed, then"
-    echo "add -f to the command line."
+    echo "Error: ${orig_ws} is not a git workspace"
     exit 2
 fi
 
-# NOTE: the hlc.gc.pregen grade that we use below *requires* these settings.
-#
-NUM_TAG_BITS=2
-BITS_PER_WORD=32
-BYTES_PER_WORD=4
-UNBOXED_FLOATS=no
+if test ! -f "${orig_ws}/library/private_builtin.m"
+then
+    echo "Error: ${orig_ws} is not a Mercury git workspace"
+    exit 2
+fi
 
-# Clean up any leftover stage[23] directories in the workspace,
-# since 'git clean' doesn't completely remove them.
-#
-/bin/rm -rf stage2 stage3
+case "${tar_file_name}" in
+    /*)
+        ;;
+    *)
+        echo "Error: ${tar_file_name} is not an absolute path name"
+        exit 2
+        ;;
+esac
 
+srcdist_name="mercury-srcdist-${version}"
+srcdist_dir="${TMPDIR}/${srcdist_name}"
+
+if test -e "${srcdist_dir}"
+then
+    echo "Error: the name of the temporary directory ${srcdist_dir} is in use"
+    exit 3
+fi
+
+cp -rp "${orig_ws}" "${srcdist_dir}"
+cd "${srcdist_dir}"
+
+/bin/rm -rf stage2 stage3 Mmake.params Mmake.stage.params
 # git checkout -- VERSION
 git submodule deinit -f .
 git clean -d -f -x
 git rev-parse HEAD > COMMIT_ID
-if test -n "${RELEASE_VERSION}"
+if test "${UPDATE_VERSION_FILE}" = "yes"
 then
-    sed "s/VERSION=.*/VERSION=${RELEASE_VERSION}/" VERSION > VERSION.new
+    sed "s/VERSION=.*/VERSION=${version}/" VERSION > VERSION.new
     mv VERSION.new VERSION
 fi
-/bin/rm -f Mmake.params Mmake.stage.params
 ./prepare.sh
+# NOTE: the hlc.gc.pregen grade that we use *requires* these settings.
+NUM_TAG_BITS=2
+BITS_PER_WORD=32
+BYTES_PER_WORD=4
+UNBOXED_FLOATS=no
 mercury_cv_low_tag_bits=${NUM_TAG_BITS} \
 mercury_cv_bits_per_word=${BITS_PER_WORD} \
 mercury_cv_bytes_per_word=${BYTES_PER_WORD} \
@@ -124,6 +161,17 @@ sh configure --with-cc="${CC}" &&
 mmake \
     TAR="${TAR}" \
     GRADE=hlc.gc.pregen \
-    MMAKEFLAGS="EXTRA_MCFLAGS='-O5 --opt-space' \
-    -j${PARALLEL}" \
+    MMAKEFLAGS="EXTRA_MCFLAGS='-O5 --opt-space' -j${PARALLEL}" \
+    SRCDIST_NAME="${srcdist_name}" \
+    TAR_FILE_NAME="${tar_file_name}" \
     tar
+
+if test "${LEAVE_TMP_DIR}" = "yes"
+then
+    echo "leaving build directory in ${TMPDIR}/build_srcdist.$$"
+    mv "${srcdist_dir}" "${TMPDIR}/build_srcdist.$$"
+else
+    /bin/rm -fr "${srcdist_dir}"
+fi
+
+exit 0
