Checkout the `clpr' directory as mercury/extras/clpr on
Estimated hours taken: 0.25

tools/test_mercury:
	Checkout the `clpr' directory as mercury/extras/clpr on
	murlibobo (so it will get included in the distribution)
	and on kryten (so it can be tested).
	On kryten, run the usual tests in the `asm_fast.gc.tr' grade,
	and also test the `clpr' directory; change the optimization level
	from `-O3' to `-O1', to reduce testing times (currently about
	12 hrs on kryten).

diff --git a/tools/test_mercury b/tools/test_mercury
--- a/tools/test_mercury
+++ b/tools/test_mercury
@@ -46,7 +46,7 @@ CHECKOUT_OPTS=-A
 case $HOST in
 	# test things at different optimization levels...
 	murlibobo)	OPTIMIZE=-O5 ;;
-	kryten) 	OPTIMIZE=-O4 ;;
+	kryten) 	OPTIMIZE=-O1 ;;
 	mercury) 	OPTIMIZE=-O3 ;;
 	muse)		OPTIMIZE=-O0 ;;
 	munta)		OPTIMIZE=-O0 ;;
@@ -148,9 +148,17 @@ echo "test_mercury starting cvs checkout at `date`" 1>&2
 
 set -x	# trace execution
 
-: checkout the sources and make sure the installation directory exists
+: checkout the sources
 cd $DIR || { false; exit 1; }
 cvs checkout $CHECKOUT_OPTS mercury tests || { false; exit 1; }
+case $HOST in
+	murlibobo|kryten)
+		(cd mercury/extras && cvs checkout $CHECKOUT_OPTS clpr) ||
+			{ false; exit 1; }
+		;;
+esac
+
+: make sure the installation directory exists
 [ -d $INSTALL_DIR ] || mkdir -p $INSTALL_DIR
 
 : update the VERSION file to specify the version we are building
@@ -313,7 +321,8 @@ case $HOST in
 	kryten)
 		GRADES="none jump fast asm_jump asm_fast none.gc
 			jump.gc fast.gc asm_jump.gc
-			asm_fast.gc asm_fast.gc.prof asm_fast.prof"
+			asm_fast.gc asm_fast.gc.prof asm_fast.prof
+			asm_fast.gc.tr"
 		;;
 	muse|munta)
 		GRADES="reg.gc asm_fast asm_fast.gc
@@ -347,7 +356,19 @@ do
 			;;
 	esac
 done
+cd ..
 
+: test the CLPR interface
+case $HOST in
+	kryten)
+		(cd mercury/extras/clpr &&
+		 mmake depend	$PARALLEL MMAKEFLAGS=$PARALLEL &&
+		 mmake 		$PARALLEL MMAKEFLAGS=$PARALLEL &&
+		 mmake check	$PARALLEL MMAKEFLAGS=$PARALLEL &&
+		 mmake install	$PARALLEL MMAKEFLAGS=$PARALLEL) ||
+			status=1
+		;;
+esac
 
 #-----------------------------------------------------------------------------#
 
@@ -374,6 +395,8 @@ case $status in
 	;;
     *)
 	: one or more tests failed
+	echo "some tests failed" 1>&2
+	fgrep '**' $TESTDIR/logs/test_mercury_$HOST
 	echo "test_mercury exiting unsuccessfully at `date`" 1>&2
 	false
 	exit 1
