Merge changes from the trunk.  Pretty much every file affected.
Estimated hours taken: 8

Merge changes from the trunk.  Pretty much every file affected.

diff --git a/tools/test_mercury b/tools/test_mercury
--- a/tools/test_mercury
+++ b/tools/test_mercury
@@ -46,7 +46,7 @@ CHECKOUT_OPTS=-A
 case $HOST in
 	# test things at different optimization levels...
 	murlibobo)	OPTIMIZE=-O5 ;;
-	kryten) 	OPTIMIZE=-O4 ;;
+	kryten) 	OPTIMIZE=-O1 ;;
 	mercury) 	OPTIMIZE=-O3 ;;
 	muse)		OPTIMIZE=-O0 ;;
 	munta)		OPTIMIZE=-O0 ;;
@@ -148,9 +148,17 @@ echo "test_mercury starting cvs checkout at `date`" 1>&2
 
 set -x	# trace execution
 
-: checkout the sources and make sure the installation directory exists
+: checkout the sources
 cd $DIR || { false; exit 1; }
 cvs checkout $CHECKOUT_OPTS mercury tests || { false; exit 1; }
+case $HOST in
+	murlibobo|kryten|mercury)
+		(cd mercury/extras && cvs checkout $CHECKOUT_OPTS clpr) ||
+			{ false; exit 1; }
+		;;
+esac
+
+: make sure the installation directory exists
 [ -d $INSTALL_DIR ] || mkdir -p $INSTALL_DIR
 
 : update the VERSION file to specify the version we are building
@@ -239,18 +247,21 @@ case $status in 0)
 		 	MMAKEFLAGS=$PARALLEL \
 		) || status=1
 		;;
-	kryten)
+	kryten|murlibobo)
 		mmake install MMAKEFLAGS=$PARALLEL || status=1
 		mmake install_split_library LIBGRADES= MMAKEFLAGS=$PARALLEL \
 			|| status=1
-		# install the asm_fast.gc.tr grade
-		mmake install_grades LIBGRADES="asm_fast.gc.tr" \
+		# install the asm_fast.gc.tr and asm_fast.tr grades
+		mmake install_grades LIBGRADES="asm_fast.gc.tr asm_fast.tr" \
 			MMAKEFLAGS="$PARALLEL" || status=1
 		;;
 	*)
 		mmake install MMAKEFLAGS=$PARALLEL || status=1
 		mmake install_split_library LIBGRADES= MMAKEFLAGS=$PARALLEL \
 			|| status=1
+		# install the asm_fast.gc.tr grade
+		mmake install_grades LIBGRADES="asm_fast.gc.tr" \
+			MMAKEFLAGS="$PARALLEL" || status=1
 		;;
     esac
     case $install_anyway in
@@ -262,6 +273,35 @@ esac
 
 [ -d $TESTDIR/logs ] || mkdir -p $TESTDIR/logs
 date >> $TESTDIR/logs/install.$HOST
+
+#-----------------------------------------------------------------------------#
+
+: test and install the CLPR interface
+case $HOST in
+	kryten|murlibobo)
+		GRADES="asm_fast.gc.tr asm_fast.tr"
+		;;
+	mercury)
+		GRADES="asm_fast.gc.tr"
+		;;
+	*)
+		GRADES=""
+		;;
+esac
+for grade in $GRADES kludge_for_broken_shells
+do
+	if [ "$GRADE" != kludge_for_broken_shells ]; then
+		echo "tests clpr stuff for grade $grade" 1>&2
+		(cd mercury/extras/clpr &&
+			 mmake realclean $PARALLEL MMAKEFLAGS=$PARALLEL &&
+			 mmake depend	$PARALLEL MMAKEFLAGS=$PARALLEL &&
+			 mmake 		$PARALLEL MMAKEFLAGS=$PARALLEL &&
+			 mmake check	$PARALLEL MMAKEFLAGS=$PARALLEL &&
+			 mmake install	$PARALLEL MMAKEFLAGS=$PARALLEL &&
+			 mmake realclean $PARALLEL MMAKEFLAGS=$PARALLEL) ||
+				status=1
+	fi
+done
 
 #-----------------------------------------------------------------------------#
 
@@ -287,7 +327,8 @@ case $HOST in murlibobo)
 	mmake MMAKEFLAGS='EXTRA_MCFLAGS="-O5 --opt-space" -j6' tar &&
 	cd .. &&
 	rm -f mercury-latest-unstable/* &&
-	mv mercury-$version.tar.gz mercury-latest-unstable
+	mv mercury-$version.tar.gz mercury-latest-unstable &&
+	mv mercury-$version-extras.tar.gz mercury-latest-unstable
 	} || status=1
 	;;
 esac
@@ -313,7 +354,8 @@ case $HOST in
 	kryten)
 		GRADES="none jump fast asm_jump asm_fast none.gc
 			jump.gc fast.gc asm_jump.gc
-			asm_fast.gc asm_fast.gc.prof asm_fast.prof"
+			asm_fast.gc asm_fast.gc.prof asm_fast.prof
+			asm_fast.gc.tr"
 		;;
 	muse|munta)
 		GRADES="reg.gc asm_fast asm_fast.gc
@@ -347,7 +389,7 @@ do
 			;;
 	esac
 done
-
+cd ..
 
 #-----------------------------------------------------------------------------#
 
@@ -363,8 +405,12 @@ case $status in
 	    rm -f mercury-latest-stable/* &&
 	    ln mercury-latest-unstable/mercury-$version.tar.gz \
 	        mercury-latest-stable/mercury-$version.tar.gz &&
+	    ln mercury-latest-unstable/mercury-$version-extras.tar.gz \
+	        mercury-latest-stable/mercury-$version-extras.tar.gz &&
 	    rm -f /home/tsa/ftp/pub/mercury/beta-releases/mercury-rotd-*.tar.gz
 	    cp mercury-latest-stable/mercury-$version.tar.gz \
+	        /home/tsa/ftp/pub/mercury/beta-releases
+	    cp mercury-latest-stable/mercury-$version-extras.tar.gz \
 	        /home/tsa/ftp/pub/mercury/beta-releases
 	    ;;
 	esac
@@ -374,6 +420,7 @@ case $status in
 	;;
     *)
 	: one or more tests failed
+	echo "some tests failed" 1>&2
 	echo "test_mercury exiting unsuccessfully at `date`" 1>&2
 	false
 	exit 1
